# DataFrames II: Filtering Data

In [1]:
import pandas as pd

## This Module's Dataset + Memory Optimization

In [2]:
employees = pd.read_csv("employees.csv")
employees.head()

,First Name,Gender,Start Date,Last Login Time,Salary,Bonus %,Senior Management,Team
0,Douglas,Male,8/6/1993,12:42 PM,97308,6.945,True,Marketing
1,Thomas,Male,3/31/1996,6:53 AM,61933,4.170,True,NaN
2,Maria,Female,4/23/1993,11:17 AM,130590,11.858,False,Finance
3,Jerry,Male,3/4/2005,1:00 PM,138705,9.340,True,Finance
4,Larry,Male,1/24/1998,4:47 PM,101004,1.389,True,Client Services

- The `info` method shows a summary of the `DataFrame` including missing values and data types.

In [3]:
employees.info()

<class 'pandas.DataFrame'>
RangeIndex: 1000 entries, 0 to 999
Data columns (total 8 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   First Name         933 non-null    str
 1   Gender             855 non-null    str
 2   Start Date         1000 non-null   str
 3   Last Login Time    1000 non-null   str
 4   Salary             1000 non-null   int64
 5   Bonus %            1000 non-null   float64
 6   Senior Management  933 non-null    object
 7   Team               957 non-null    str
dtypes: float64(1), int64(1), object(1), str(5)
memory usage: 98.3+ KB

- The `pd.to_datetime`function method converts a `Series` to hold datetime values.
- The `format` parameter informs pandas of the format that the times are stored in.
- We pass symbols designating the segments of the string. For example, `%m` is for month and `%d` is for day.
- Use the `astype` method to convert the values in a `Series` to another type.

In [4]:
employees["Start Date"].head()

0     8/6/1993
1    3/31/1996
2    4/23/1993
3     3/4/2005
4    1/24/1998
Name: Start Date, dtype: str

In [5]:
employees["Start Date"] = pd.to_datetime(employees["Start Date"], format="%m/%d/%Y")

- The `dt` attribute reveals an object with many datetime-related attributes and methods.
- The `dt.time` attribute extracts only the time from each value in a datetime `Series`.

In [6]:
employees["Last Login Time"].head()

0    12:42 PM
1     6:53 AM
2    11:17 AM
3     1:00 PM
4     4:47 PM
Name: Last Login Time, dtype: str

In [7]:
employees["Last Login Time"] = pd.to_datetime(
    employees["Last Login Time"], format="%H:%M %p"
).dt.time

- Let's convert the `Senior Management` column into a Boolean column.
- Let's convert the `Gender` column into a category column.

In [8]:
employees["Senior Management"] = employees["Senior Management"].astype(bool)
employees["Gender"] = employees["Gender"].astype("category")
employees["Team"] = employees["Team"].astype("category")

In [9]:
employees.info()

<class 'pandas.DataFrame'>
RangeIndex: 1000 entries, 0 to 999
Data columns (total 8 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   First Name         933 non-null    str
 1   Gender             855 non-null    category
 2   Start Date         1000 non-null   datetime64[us]
 3   Last Login Time    1000 non-null   object
 4   Salary             1000 non-null   int64
 5   Bonus %            1000 non-null   float64
 6   Senior Management  1000 non-null   bool
 7   Team               957 non-null    category
dtypes: bool(1), category(2), datetime64[us](1), float64(1), int64(1), object(1), str(1)
memory usage: 47.7+ KB

In [10]:
employees = pd.read_csv("employees.csv").astype(
    {"Senior Management": bool, "Gender": "category", "Team": "category"}
)

employees["Start Date"] = pd.to_datetime(employees["Start Date"], format="%m/%d/%Y")
employees["Last Login Time"] = pd.to_datetime(
    employees["Last Login Time"], format="%H:%M %p"
).dt.time

employees.head()

,First Name,Gender,Start Date,Last Login Time,Salary,Bonus %,Senior Management,Team
0,Douglas,Male,1993-08-06,12:42:00,97308,6.945,True,Marketing
1,Thomas,Male,1996-03-31,06:53:00,61933,4.170,True,NaN
2,Maria,Female,1993-04-23,11:17:00,130590,11.858,False,Finance
3,Jerry,Male,2005-03-04,01:00:00,138705,9.340,True,Finance
4,Larry,Male,1998-01-24,04:47:00,101004,1.389,True,Client Services

## Filter A DataFrame  Based On A Condition
- Pandas needs a Boolean `Series` to perform a filter.
- Pass the Boolean `Series` inside square brackets after the `DataFrame`.

In [11]:
employees = pd.read_csv("employees.csv").astype(
    {"Senior Management": bool, "Gender": "category", "Team": "category"}
)

employees["Start Date"] = pd.to_datetime(employees["Start Date"], format="%m/%d/%Y")
employees["Last Login Time"] = pd.to_datetime(
    employees["Last Login Time"], format="%H:%M %p"
).dt.time

employees.head()

,First Name,Gender,Start Date,Last Login Time,Salary,Bonus %,Senior Management,Team
0,Douglas,Male,1993-08-06,12:42:00,97308,6.945,True,Marketing
1,Thomas,Male,1996-03-31,06:53:00,61933,4.170,True,NaN
2,Maria,Female,1993-04-23,11:17:00,130590,11.858,False,Finance
3,Jerry,Male,2005-03-04,01:00:00,138705,9.340,True,Finance
4,Larry,Male,1998-01-24,04:47:00,101004,1.389,True,Client Services

In [12]:
5 == 6
5 != 10

True

In [13]:
employees[employees["Gender"] == "Male"]
employees[employees["Gender"] != "Male"]
employees[employees["Team"] == "Finance"]

,First Name,Gender,Start Date,Last Login Time,Salary,Bonus %,Senior Management,Team
2,Maria,Female,1993-04-23,11:17:00,130590,11.858,False,Finance
3,Jerry,Male,2005-03-04,01:00:00,138705,9.340,True,Finance
7,NaN,Female,2015-07-20,10:43:00,45906,11.598,True,Finance
14,Kimberly,Female,1999-01-14,07:13:00,41426,14.543,True,Finance
46,Bruce,Male,2009-11-28,10:47:00,114796,6.796,False,Finance
...,...,...,...,...,...,...,...,...
907,Elizabeth,Female,1998-07-27,11:12:00,137144,10.081,False,Finance
954,Joe,Male,1980-01-19,04:06:00,119667,1.148,True,Finance
987,Gloria,Female,2014-12-08,05:08:00,136709,10.331,True,Finance
992,Anthony,Male,2011-10-16,08:35:00,112769,11.625,True,Finance
996,Phillip,Male,1984-01-31,06:30:00,42392,19.675,False,Finance

- Assign the Boolean `Series` to a variable for a simpler syntax.

In [14]:
on_finance_team = employees["Team"] == "Finance"
employees[on_finance_team]

,First Name,Gender,Start Date,Last Login Time,Salary,Bonus %,Senior Management,Team
2,Maria,Female,1993-04-23,11:17:00,130590,11.858,False,Finance
3,Jerry,Male,2005-03-04,01:00:00,138705,9.340,True,Finance
7,NaN,Female,2015-07-20,10:43:00,45906,11.598,True,Finance
14,Kimberly,Female,1999-01-14,07:13:00,41426,14.543,True,Finance
46,Bruce,Male,2009-11-28,10:47:00,114796,6.796,False,Finance
...,...,...,...,...,...,...,...,...
907,Elizabeth,Female,1998-07-27,11:12:00,137144,10.081,False,Finance
954,Joe,Male,1980-01-19,04:06:00,119667,1.148,True,Finance
987,Gloria,Female,2014-12-08,05:08:00,136709,10.331,True,Finance
992,Anthony,Male,2011-10-16,08:35:00,112769,11.625,True,Finance
996,Phillip,Male,1984-01-31,06:30:00,42392,19.675,False,Finance

- An existing Boolean column can serve as a filter.

In [15]:
employees[employees["Senior Management"]]

,First Name,Gender,Start Date,Last Login Time,Salary,Bonus %,Senior Management,Team
0,Douglas,Male,1993-08-06,12:42:00,97308,6.945,True,Marketing
1,Thomas,Male,1996-03-31,06:53:00,61933,4.170,True,NaN
3,Jerry,Male,2005-03-04,01:00:00,138705,9.340,True,Finance
4,Larry,Male,1998-01-24,04:47:00,101004,1.389,True,Client Services
6,Ruby,Female,1987-08-17,04:20:00,65476,10.012,True,Product
...,...,...,...,...,...,...,...,...
991,Rose,Female,2002-08-25,05:12:00,134505,11.051,True,Marketing
992,Anthony,Male,2011-10-16,08:35:00,112769,11.625,True,Finance
993,Tina,Female,1997-05-15,03:53:00,56450,19.040,True,Engineering
994,George,Male,2013-06-21,05:47:00,98874,4.479,True,Marketing
999,Albert,Male,2012-05-15,06:24:00,129949,10.169,True,Sales

- We can generate a Boolean `Series` using a wide variety of operations (equality, inequality, less than, greater than, inclusion, etc)

In [16]:
employees[employees["Salary"] > 110000]

employees[employees["Bonus %"] < 1.5]

,First Name,Gender,Start Date,Last Login Time,Salary,Bonus %,Senior Management,Team
4,Larry,Male,1998-01-24,04:47:00,101004,1.389,True,Client Services
15,Lillian,Female,2016-06-05,06:09:00,59414,1.256,False,Product
58,Theresa,Female,2010-04-11,07:18:00,72670,1.481,True,Engineering
77,Charles,Male,2004-09-14,08:13:00,107391,1.260,True,Marketing
175,Willie,Male,1998-02-17,08:20:00,146651,1.451,True,Engineering
189,Clarence,Male,1998-05-02,03:16:00,85700,1.215,False,Sales
217,Douglas,Male,1999-09-03,04:00:00,83341,1.015,True,Client Services
273,Nicholas,Male,1994-04-12,08:21:00,74669,1.113,True,Product
279,Ruby,Female,2000-11-08,07:35:00,105946,1.139,False,Business Development
365,Gloria,NaN,1983-07-19,01:57:00,140885,1.113,False,Human Resources
445,Chris,Male,2006-12-12,01:57:00,71642,1.496,False,NaN
481,NaN,Female,2013-04-27,06:40:00,93847,1.085,True,Business Development
527,Helen,NaN,1993-12-02,01:42:00,45724,1.022,False,Product
570,Kelly,Female,1996-08-16,03:09:00,41427,1.431,False,Product
578,Amanda,Female,1982-03-17,11:46:00,107111,1.438,True,Product
579,Harold,Male,2010-10-18,08:45:00,65673,1.187,True,Legal
617,Kathy,Female,2001-01-14,05:11:00,45682,1.451,True,Marketing
618,Peter,Male,1992-11-24,05:43:00,69297,1.268,False,Finance
638,Frances,Female,1996-11-12,06:08:00,112467,1.433,False,Business Development
652,Willie,Male,2009-12-05,05:39:00,141932,1.017,True,Engineering
708,Steve,Male,2002-01-11,09:17:00,51821,1.197,True,Legal
732,Henry,Male,1986-05-12,02:04:00,59943,1.432,False,Finance
734,NaN,Female,1994-12-18,08:42:00,138807,1.400,True,Human Resources
746,Gloria,Female,2004-08-19,10:31:00,46602,1.027,True,Business Development
912,Joe,Male,1998-12-08,10:28:00,126120,1.020,False,NaN
929,Theresa,Female,2001-04-27,09:17:00,75661,1.079,True,Legal
954,Joe,Male,1980-01-19,04:06:00,119667,1.148,True,Finance
997,Russell,Male,2013-05-20,12:39:00,96914,1.421,False,Product

In [17]:
employees[employees["Start Date"] < "1985-01-01"]

,First Name,Gender,Start Date,Last Login Time,Salary,Bonus %,Senior Management,Team
10,Louise,Female,1980-08-12,09:01:00,63241,15.132,True,NaN
12,Brandon,Male,1980-12-01,01:08:00,112807,17.492,True,Human Resources
18,Diana,Female,1981-10-23,10:27:00,132940,19.082,False,Client Services
28,Terry,Male,1981-11-27,06:30:00,124008,13.464,True,Client Services
37,Linda,Female,1981-10-19,08:49:00,57427,9.557,True,Client Services
...,...,...,...,...,...,...,...,...
982,Rose,Female,1982-04-06,10:43:00,91411,8.639,True,Human Resources
983,John,Male,1982-12-23,10:35:00,146907,11.738,False,Engineering
985,Stephen,NaN,1983-07-10,08:10:00,85668,1.909,False,Legal
986,Donna,Female,1982-11-26,07:04:00,82871,17.999,False,Marketing
996,Phillip,Male,1984-01-31,06:30:00,42392,19.675,False,Finance

In [18]:
import datetime as dt

In [19]:
employees[employees["Last Login Time"] < dt.time(12, 0, 0)]

,First Name,Gender,Start Date,Last Login Time,Salary,Bonus %,Senior Management,Team
1,Thomas,Male,1996-03-31,06:53:00,61933,4.170,True,NaN
2,Maria,Female,1993-04-23,11:17:00,130590,11.858,False,Finance
3,Jerry,Male,2005-03-04,01:00:00,138705,9.340,True,Finance
4,Larry,Male,1998-01-24,04:47:00,101004,1.389,True,Client Services
5,Dennis,Male,1987-04-18,01:35:00,115163,10.125,False,Legal
...,...,...,...,...,...,...,...,...
994,George,Male,2013-06-21,05:47:00,98874,4.479,True,Marketing
995,Henry,NaN,2014-11-23,06:09:00,132483,16.655,False,Distribution
996,Phillip,Male,1984-01-31,06:30:00,42392,19.675,False,Finance
998,Larry,Male,2013-04-20,04:45:00,60500,11.985,False,Business Development
999,Albert,Male,2012-05-15,06:24:00,129949,10.169,True,Sales

## Filter with More than One Condition (AND)

In [20]:
employees = pd.read_csv("employees.csv").astype(
    {"Senior Management": bool, "Gender": "category", "Team": "category"}
)

employees["Start Date"] = pd.to_datetime(employees["Start Date"], format="%m/%d/%Y")
employees["Last Login Time"] = pd.to_datetime(
    employees["Last Login Time"], format="%H:%M %p"
).dt.time

employees.head()

,First Name,Gender,Start Date,Last Login Time,Salary,Bonus %,Senior Management,Team
0,Douglas,Male,1993-08-06,12:42:00,97308,6.945,True,Marketing
1,Thomas,Male,1996-03-31,06:53:00,61933,4.170,True,NaN
2,Maria,Female,1993-04-23,11:17:00,130590,11.858,False,Finance
3,Jerry,Male,2005-03-04,01:00:00,138705,9.340,True,Finance
4,Larry,Male,1998-01-24,04:47:00,101004,1.389,True,Client Services

- Add the `&` operator in between two Boolean `Series` to filter by multiple conditions.
- Add parentheses around the individual `Series` to avoid errors/confusion.

In [21]:
# female employees who work in Marketing
employees[(employees["Gender"] == "Female") & (employees["Team"] == "Marketing")]

,First Name,Gender,Start Date,Last Login Time,Salary,Bonus %,Senior Management,Team
43,Marilyn,Female,1980-12-07,03:16:00,73524,5.207,True,Marketing
62,NaN,Female,2007-06-12,05:25:00,58112,19.414,True,Marketing
98,Tina,Female,2016-06-16,07:47:00,100705,16.961,True,Marketing
140,Shirley,Female,1981-02-28,01:23:00,113850,1.854,False,Marketing
158,Norma,Female,1999-02-28,08:45:00,114412,8.756,True,Marketing
201,Kimberly,Female,1997-07-15,05:57:00,36643,7.953,False,Marketing
220,NaN,Female,1991-06-17,12:49:00,71945,5.560,True,Marketing
305,Margaret,Female,1993-02-06,01:05:00,125220,3.733,False,Marketing
319,Jacqueline,Female,1981-11-25,03:01:00,145988,18.243,False,Marketing
331,Evelyn,Female,1983-09-03,01:58:00,36759,17.269,True,Marketing
379,NaN,Female,2002-09-18,12:39:00,118906,4.537,True,Marketing
446,Cheryl,Female,1994-08-16,08:33:00,67150,15.850,True,Marketing
468,Janice,Female,1997-06-28,01:48:00,136032,10.696,True,Marketing
490,Judith,Female,2007-11-23,01:22:00,117055,7.461,False,Marketing
531,Virginia,Female,2010-05-02,09:10:00,123649,10.154,True,Marketing
535,Louise,Female,1981-09-18,05:47:00,91462,8.205,False,Marketing
568,Susan,Female,1986-04-18,09:31:00,90829,19.142,False,Marketing
585,Shirley,Female,1988-04-16,11:09:00,132156,2.754,False,Marketing
586,Rose,Female,2004-10-30,04:34:00,56961,7.585,False,Marketing
617,Kathy,Female,2001-01-14,05:11:00,45682,1.451,True,Marketing
625,Cynthia,Female,2015-06-29,06:38:00,82408,8.701,True,Marketing
627,Anne,Female,1984-11-21,12:30:00,128305,16.636,False,Marketing
629,Debra,Female,1983-03-12,12:19:00,74911,19.513,False,Marketing
656,Lisa,Female,1982-02-09,06:44:00,113592,17.108,True,Marketing
675,Diane,Female,2009-10-30,06:56:00,130577,12.791,False,Marketing
676,Annie,Female,1992-06-06,10:04:00,138925,9.801,True,Marketing
730,Nicole,Female,2009-04-26,12:40:00,66047,18.674,True,Marketing
785,NaN,Female,1982-07-24,12:00:00,57811,8.941,True,Marketing
811,Judith,Female,1989-09-03,11:16:00,134048,6.818,True,Marketing
813,Evelyn,Female,2002-02-10,04:44:00,123621,19.767,True,Marketing
817,Ruby,Female,2008-05-31,08:41:00,83112,4.083,False,Marketing
824,Julia,Female,2014-08-18,03:12:00,97566,2.147,False,Marketing
881,Ruby,Female,1980-01-28,11:08:00,142868,6.318,False,Marketing
883,Kathryn,Female,1995-10-27,03:39:00,57300,18.015,False,Marketing
894,Betty,Female,2002-11-19,10:40:00,37005,7.645,True,Marketing
913,Lois,Female,2015-12-11,04:10:00,99747,6.168,False,Marketing
930,Nancy,Female,2001-09-10,11:57:00,85213,2.386,True,Marketing
942,Lori,Female,2015-11-20,01:15:00,75498,6.537,True,Marketing
986,Donna,Female,1982-11-26,07:04:00,82871,17.999,False,Marketing
991,Rose,Female,2002-08-25,05:12:00,134505,11.051,True,Marketing

- We can assign the `Series` to variables to make the syntax more readable.
- Variables also remove the need for parentheses.

In [22]:
is_female = employees["Gender"] == "Female"
is_in_marketing = employees["Team"] == "Marketing"
salary_over_100k = employees["Salary"] > 100000

employees[is_female & is_in_marketing & salary_over_100k].head()

,First Name,Gender,Start Date,Last Login Time,Salary,Bonus %,Senior Management,Team
98,Tina,Female,2016-06-16,07:47:00,100705,16.961,True,Marketing
140,Shirley,Female,1981-02-28,01:23:00,113850,1.854,False,Marketing
158,Norma,Female,1999-02-28,08:45:00,114412,8.756,True,Marketing
305,Margaret,Female,1993-02-06,01:05:00,125220,3.733,False,Marketing
319,Jacqueline,Female,1981-11-25,03:01:00,145988,18.243,False,Marketing

## Filter with More than One Condition (OR)
- Use the `|` operator in between two Boolean `Series` to filter by *either* condition.

In [23]:
employees = pd.read_csv("employees.csv").astype(
    {"Senior Management": bool, "Gender": "category", "Team": "category"}
)

employees["Start Date"] = pd.to_datetime(employees["Start Date"], format="%m/%d/%Y")
employees["Last Login Time"] = pd.to_datetime(
    employees["Last Login Time"], format="%H:%M %p"
).dt.time

employees.head()

,First Name,Gender,Start Date,Last Login Time,Salary,Bonus %,Senior Management,Team
0,Douglas,Male,1993-08-06,12:42:00,97308,6.945,True,Marketing
1,Thomas,Male,1996-03-31,06:53:00,61933,4.170,True,NaN
2,Maria,Female,1993-04-23,11:17:00,130590,11.858,False,Finance
3,Jerry,Male,2005-03-04,01:00:00,138705,9.340,True,Finance
4,Larry,Male,1998-01-24,04:47:00,101004,1.389,True,Client Services

- Let's target employees who are either senior management OR who started before 1990-01-01.

In [24]:
is_senior_management = employees["Senior Management"]
started_in_80s = employees["Start Date"] < "1990-01-01"

employees[is_senior_management | started_in_80s]

,First Name,Gender,Start Date,Last Login Time,Salary,Bonus %,Senior Management,Team
0,Douglas,Male,1993-08-06,12:42:00,97308,6.945,True,Marketing
1,Thomas,Male,1996-03-31,06:53:00,61933,4.170,True,NaN
3,Jerry,Male,2005-03-04,01:00:00,138705,9.340,True,Finance
4,Larry,Male,1998-01-24,04:47:00,101004,1.389,True,Client Services
5,Dennis,Male,1987-04-18,01:35:00,115163,10.125,False,Legal
...,...,...,...,...,...,...,...,...
992,Anthony,Male,2011-10-16,08:35:00,112769,11.625,True,Finance
993,Tina,Female,1997-05-15,03:53:00,56450,19.040,True,Engineering
994,George,Male,2013-06-21,05:47:00,98874,4.479,True,Marketing
996,Phillip,Male,1984-01-31,06:30:00,42392,19.675,False,Finance
999,Albert,Male,2012-05-15,06:24:00,129949,10.169,True,Sales

- Let's look for employees named Robert who work in Client Services OR have a start date after 2016-06-01.

In [25]:
is_robert = employees["First Name"] == "Robert"
is_in_client_services = employees["Team"] == "Client Services"
start_date_after_june_2016 = employees["Start Date"] > "2016-06-01"

In [26]:
employees[(is_robert & is_in_client_services) | start_date_after_june_2016]

employees[is_robert & (is_in_client_services | start_date_after_june_2016)]

# employees[is_robert & is_in_client_services | start_date_after_june_2016]

,First Name,Gender,Start Date,Last Login Time,Salary,Bonus %,Senior Management,Team
387,Robert,Male,1994-10-29,04:26:00,123294,19.894,False,Client Services

## The isin Method
- The `isin` method accepts a collection object like a list, tuple, or `Series`.
- The method returns True for a row if its value is found within the collection.

In [27]:
employees = pd.read_csv("employees.csv").astype(
    {"Senior Management": bool, "Gender": "category", "Team": "category"}
)

employees["Start Date"] = pd.to_datetime(employees["Start Date"], format="%m/%d/%Y")
employees["Last Login Time"] = pd.to_datetime(
    employees["Last Login Time"], format="%H:%M %p"
).dt.time

employees.head()

,First Name,Gender,Start Date,Last Login Time,Salary,Bonus %,Senior Management,Team
0,Douglas,Male,1993-08-06,12:42:00,97308,6.945,True,Marketing
1,Thomas,Male,1996-03-31,06:53:00,61933,4.170,True,NaN
2,Maria,Female,1993-04-23,11:17:00,130590,11.858,False,Finance
3,Jerry,Male,2005-03-04,01:00:00,138705,9.340,True,Finance
4,Larry,Male,1998-01-24,04:47:00,101004,1.389,True,Client Services

- Let's say we're targeting employees whose team is Legal, Sales, or Product.

In [28]:
legal_team = employees["Team"] == "Legal"
sales_team = employees["Team"] == "Sales"
product_team = employees["Team"] == "Product"

employees[legal_team | sales_team | product_team]

,First Name,Gender,Start Date,Last Login Time,Salary,Bonus %,Senior Management,Team
5,Dennis,Male,1987-04-18,01:35:00,115163,10.125,False,Legal
6,Ruby,Female,1987-08-17,04:20:00,65476,10.012,True,Product
11,Julie,Female,1997-10-26,03:19:00,102508,12.637,True,Legal
13,Gary,Male,2008-01-27,11:40:00,109831,5.831,False,Sales
15,Lillian,Female,2016-06-05,06:09:00,59414,1.256,False,Product
...,...,...,...,...,...,...,...,...
981,James,Male,1993-01-15,05:19:00,148985,19.280,False,Legal
985,Stephen,NaN,1983-07-10,08:10:00,85668,1.909,False,Legal
989,Justin,NaN,1991-02-10,04:58:00,38344,3.794,False,Legal
997,Russell,Male,2013-05-20,12:39:00,96914,1.421,False,Product
999,Albert,Male,2012-05-15,06:24:00,129949,10.169,True,Sales

In [29]:
target_teams = employees["Team"].isin(["Legal", "Sales", "Product"])
employees[target_teams]

,First Name,Gender,Start Date,Last Login Time,Salary,Bonus %,Senior Management,Team
5,Dennis,Male,1987-04-18,01:35:00,115163,10.125,False,Legal
6,Ruby,Female,1987-08-17,04:20:00,65476,10.012,True,Product
11,Julie,Female,1997-10-26,03:19:00,102508,12.637,True,Legal
13,Gary,Male,2008-01-27,11:40:00,109831,5.831,False,Sales
15,Lillian,Female,2016-06-05,06:09:00,59414,1.256,False,Product
...,...,...,...,...,...,...,...,...
981,James,Male,1993-01-15,05:19:00,148985,19.280,False,Legal
985,Stephen,NaN,1983-07-10,08:10:00,85668,1.909,False,Legal
989,Justin,NaN,1991-02-10,04:58:00,38344,3.794,False,Legal
997,Russell,Male,2013-05-20,12:39:00,96914,1.421,False,Product
999,Albert,Male,2012-05-15,06:24:00,129949,10.169,True,Sales

## The isnull and notnull Methods
- The `isnull` method returns True for `NaN` values in a `Series`.
- The `notnull` method returns True for present values in a `Series`.
- The `isna` method is an alias for `isnull`.
- The `notna` method is an alias for `notnull`.

In [30]:
employees = pd.read_csv("employees.csv").astype(
    {"Senior Management": bool, "Gender": "category", "Team": "category"}
)

employees["Start Date"] = pd.to_datetime(employees["Start Date"], format="%m/%d/%Y")
employees["Last Login Time"] = pd.to_datetime(
    employees["Last Login Time"], format="%H:%M %p"
).dt.time

employees.head()

,First Name,Gender,Start Date,Last Login Time,Salary,Bonus %,Senior Management,Team
0,Douglas,Male,1993-08-06,12:42:00,97308,6.945,True,Marketing
1,Thomas,Male,1996-03-31,06:53:00,61933,4.170,True,NaN
2,Maria,Female,1993-04-23,11:17:00,130590,11.858,False,Finance
3,Jerry,Male,2005-03-04,01:00:00,138705,9.340,True,Finance
4,Larry,Male,1998-01-24,04:47:00,101004,1.389,True,Client Services

In [31]:
employees[employees["Team"].isnull()]
employees[employees["Team"].isna()]

,First Name,Gender,Start Date,Last Login Time,Salary,Bonus %,Senior Management,Team
1,Thomas,Male,1996-03-31,06:53:00,61933,4.170,True,NaN
10,Louise,Female,1980-08-12,09:01:00,63241,15.132,True,NaN
23,NaN,Male,2012-06-14,04:19:00,125792,5.042,True,NaN
32,NaN,Male,1998-08-21,02:27:00,122340,6.417,True,NaN
91,James,NaN,2005-01-26,11:00:00,128771,8.309,False,NaN
109,Christopher,Male,2000-04-22,10:15:00,37919,11.449,False,NaN
139,NaN,Female,1990-10-03,01:08:00,132373,10.527,True,NaN
199,Jonathan,Male,2009-07-17,08:15:00,130581,16.736,True,NaN
258,Michael,Male,2002-01-24,03:04:00,43586,12.659,False,NaN
290,Jeremy,Male,1988-06-14,06:20:00,129460,13.657,True,NaN
314,Bobby,Male,1996-03-31,05:40:00,112117,6.338,False,NaN
367,Edward,Male,1989-08-04,06:06:00,66067,10.957,True,NaN
382,NaN,Female,1996-04-18,03:57:00,107024,12.182,True,NaN
434,Joyce,Female,1995-02-07,07:38:00,50701,14.227,True,NaN
438,Jason,Male,1998-11-20,02:54:00,69244,6.220,True,NaN
445,Chris,Male,2006-12-12,01:57:00,71642,1.496,False,NaN
479,Richard,Male,1997-07-04,11:47:00,47647,18.787,True,NaN
512,Wanda,Female,1993-04-06,03:11:00,78883,19.695,False,NaN
513,Jimmy,Male,2013-11-19,07:29:00,63549,19.624,False,NaN
520,Peter,Male,2003-02-22,09:09:00,56580,8.411,True,NaN
567,NaN,Female,1980-04-01,08:04:00,48141,12.605,True,NaN
573,Kimberly,Female,1981-12-30,04:51:00,81800,5.435,True,NaN
580,Harry,Male,1985-01-27,08:18:00,65482,18.089,False,NaN
626,NaN,Female,1997-04-13,08:03:00,131755,2.930,True,NaN
634,Carl,Male,1987-03-30,05:59:00,75598,19.289,False,NaN
635,Randy,Male,2000-09-27,03:04:00,89831,13.047,True,NaN
647,Donald,Male,1988-04-06,10:00:00,122920,5.320,False,NaN
669,Joseph,NaN,1982-03-28,01:05:00,86564,11.879,True,NaN
684,Alice,Female,2016-01-21,05:07:00,117787,10.485,False,NaN
706,Todd,Male,1993-07-04,06:53:00,128175,18.473,True,NaN
726,Daniel,Male,2016-02-29,04:04:00,77287,13.000,True,NaN
753,Antonio,Male,1999-06-06,10:54:00,41928,5.478,True,NaN
774,NaN,Female,2000-06-18,07:36:00,106428,10.867,True,NaN
781,Lawrence,Male,1995-07-03,10:55:00,46378,9.127,False,NaN
794,Nicole,Female,2004-03-01,05:17:00,44021,10.286,False,NaN
826,NaN,NaN,1988-08-01,01:35:00,87103,5.665,True,NaN
850,Charles,Male,1997-09-03,10:04:00,148291,6.002,False,NaN
851,Bobby,Male,1996-08-19,01:16:00,147842,16.158,True,NaN
853,Mildred,Female,2007-04-06,10:06:00,139284,11.390,True,NaN
855,Phillip,NaN,2003-10-20,11:09:00,89700,2.277,True,NaN
864,Ryan,Male,2012-11-16,01:47:00,57292,6.010,False,NaN
912,Joe,Male,1998-12-08,10:28:00,126120,1.020,False,NaN
951,NaN,Female,2010-09-14,05:19:00,143638,9.662,True,NaN

In [32]:
employees[employees["Team"].notnull()]
employees[employees["Team"].notna()]

,First Name,Gender,Start Date,Last Login Time,Salary,Bonus %,Senior Management,Team
0,Douglas,Male,1993-08-06,12:42:00,97308,6.945,True,Marketing
2,Maria,Female,1993-04-23,11:17:00,130590,11.858,False,Finance
3,Jerry,Male,2005-03-04,01:00:00,138705,9.340,True,Finance
4,Larry,Male,1998-01-24,04:47:00,101004,1.389,True,Client Services
5,Dennis,Male,1987-04-18,01:35:00,115163,10.125,False,Legal
...,...,...,...,...,...,...,...,...
995,Henry,NaN,2014-11-23,06:09:00,132483,16.655,False,Distribution
996,Phillip,Male,1984-01-31,06:30:00,42392,19.675,False,Finance
997,Russell,Male,2013-05-20,12:39:00,96914,1.421,False,Product
998,Larry,Male,2013-04-20,04:45:00,60500,11.985,False,Business Development
999,Albert,Male,2012-05-15,06:24:00,129949,10.169,True,Sales

In [33]:
employees[employees["First Name"].isnull() & employees["Team"].notnull()]

,First Name,Gender,Start Date,Last Login Time,Salary,Bonus %,Senior Management,Team
7,NaN,Female,2015-07-20,10:43:00,45906,11.598,True,Finance
25,NaN,Male,2012-10-08,01:12:00,37076,18.576,True,Client Services
39,NaN,Male,2016-01-29,02:33:00,122173,7.797,True,Client Services
51,NaN,NaN,2011-12-17,08:29:00,41126,14.009,True,Sales
62,NaN,Female,2007-06-12,05:25:00,58112,19.414,True,Marketing
116,NaN,Male,1991-06-22,08:58:00,76189,18.988,True,Legal
149,NaN,Female,2014-08-17,02:00:00,86230,8.578,True,Distribution
157,NaN,Female,2005-07-27,08:32:00,79536,14.443,True,Product
165,NaN,Female,2014-03-23,01:28:00,59148,9.061,True,Legal
166,NaN,Female,1991-07-09,06:52:00,42341,7.014,True,Sales
174,NaN,NaN,2007-09-18,06:59:00,40297,6.185,True,Client Services
186,NaN,Female,2005-02-23,09:50:00,149654,1.825,True,Sales
220,NaN,Female,1991-06-17,12:49:00,71945,5.560,True,Marketing
253,NaN,NaN,2003-04-28,03:01:00,113732,10.391,True,Sales
257,NaN,Male,1999-11-25,06:16:00,42676,15.517,True,Sales
266,NaN,Female,2009-08-05,08:14:00,115145,14.063,True,Distribution
267,NaN,Male,2005-02-04,01:01:00,40451,16.044,True,Distribution
269,NaN,Female,1992-08-02,08:35:00,145316,18.517,True,Human Resources
320,NaN,Female,2008-07-08,11:40:00,62960,14.356,True,Sales
329,NaN,Male,2010-01-27,02:57:00,87760,14.987,True,Engineering
352,NaN,Male,2011-10-09,09:29:00,69906,4.844,True,Engineering
353,NaN,Male,1997-04-22,09:36:00,65078,3.095,True,Marketing
374,NaN,Female,2006-12-31,11:02:00,81444,3.171,True,Distribution
379,NaN,Female,2002-09-18,12:39:00,118906,4.537,True,Marketing
416,NaN,Male,2008-06-29,05:23:00,111043,5.966,True,Distribution
444,NaN,Male,2016-05-24,09:17:00,76409,7.008,True,Distribution
454,NaN,Male,1995-02-21,12:26:00,136602,10.429,True,Marketing
481,NaN,Female,2013-04-27,06:40:00,93847,1.085,True,Business Development
483,NaN,Female,1992-04-26,08:01:00,115436,3.099,True,Human Resources
504,NaN,Female,2014-06-24,10:05:00,38275,10.494,True,Distribution
505,NaN,Male,1980-04-20,01:17:00,71520,13.248,True,Engineering
521,NaN,NaN,1981-09-25,09:59:00,83895,17.971,True,Engineering
540,NaN,Female,2009-12-02,03:30:00,84746,4.820,True,Finance
574,NaN,Female,2009-01-13,01:01:00,118736,7.421,True,Client Services
599,NaN,Female,1990-10-11,10:57:00,98385,10.925,True,Human Resources
607,NaN,Male,1983-10-13,11:59:00,139754,12.740,True,Sales
608,NaN,Female,1993-10-24,05:17:00,116236,17.274,True,Engineering
628,NaN,NaN,1988-09-02,12:49:00,147309,1.702,True,Distribution
674,NaN,Male,2012-08-28,07:56:00,88733,1.932,True,Human Resources
685,NaN,Male,1989-10-20,09:37:00,88086,19.387,True,Finance
687,NaN,Male,1996-12-27,07:07:00,139959,8.992,True,Distribution
697,NaN,Male,1990-05-23,02:09:00,136655,9.801,True,Distribution
709,NaN,Male,1995-04-07,04:32:00,60411,12.048,True,Human Resources
733,NaN,Male,2009-06-17,01:00:00,136681,3.655,True,Business Development
734,NaN,Female,1994-12-18,08:42:00,138807,1.400,True,Human Resources
773,NaN,Male,1986-10-24,09:23:00,47176,10.736,True,Finance
782,NaN,Male,1986-05-06,04:41:00,74104,17.680,True,Client Services
783,NaN,NaN,1991-04-15,03:39:00,132505,13.592,True,Product
785,NaN,Female,1982-07-24,12:00:00,57811,8.941,True,Marketing
812,NaN,Male,1994-12-13,10:34:00,141311,5.478,True,Product
821,NaN,Female,1980-12-27,02:27:00,80399,12.254,True,Distribution
823,NaN,Male,2009-11-12,02:30:00,109411,9.494,True,Engineering
877,NaN,Male,1980-09-05,07:36:00,114896,13.823,True,Client Services
890,NaN,Male,2015-11-24,03:11:00,145329,7.100,True,Finance
902,NaN,Male,2001-05-23,07:52:00,103877,6.322,True,Distribution
925,NaN,Female,2000-08-23,04:19:00,95866,19.388,True,Sales
946,NaN,Female,1985-09-15,01:50:00,133472,16.941,True,Distribution
947,NaN,Male,2012-07-30,03:07:00,107351,5.329,True,Marketing

## The between Method
- The `between` method returns True if a `Series` value is found within its range.

In [34]:
employees = pd.read_csv("employees.csv").astype(
    {"Senior Management": bool, "Gender": "category", "Team": "category"}
)

employees["Start Date"] = pd.to_datetime(employees["Start Date"], format="%m/%d/%Y")
employees["Last Login Time"] = pd.to_datetime(
    employees["Last Login Time"], format="%H:%M %p"
).dt.time

employees.head()

,First Name,Gender,Start Date,Last Login Time,Salary,Bonus %,Senior Management,Team
0,Douglas,Male,1993-08-06,12:42:00,97308,6.945,True,Marketing
1,Thomas,Male,1996-03-31,06:53:00,61933,4.170,True,NaN
2,Maria,Female,1993-04-23,11:17:00,130590,11.858,False,Finance
3,Jerry,Male,2005-03-04,01:00:00,138705,9.340,True,Finance
4,Larry,Male,1998-01-24,04:47:00,101004,1.389,True,Client Services

In [35]:
import datetime as dt

In [36]:
employees[employees["Salary"].between(60000, 70000)]
employees[employees["Bonus %"].between(2.0, 5.0)]
employees[employees["Start Date"].between("1991-01-01", "1992-01-01")]
employees[employees["Last Login Time"].between(dt.time(8, 30), dt.time(12, 0))]

,First Name,Gender,Start Date,Last Login Time,Salary,Bonus %,Senior Management,Team
2,Maria,Female,1993-04-23,11:17:00,130590,11.858,False,Finance
7,NaN,Female,2015-07-20,10:43:00,45906,11.598,True,Finance
10,Louise,Female,1980-08-12,09:01:00,63241,15.132,True,NaN
13,Gary,Male,2008-01-27,11:40:00,109831,5.831,False,Sales
18,Diana,Female,1981-10-23,10:27:00,132940,19.082,False,Client Services
...,...,...,...,...,...,...,...,...
977,Sarah,Female,1995-12-04,09:16:00,124566,5.949,False,Product
982,Rose,Female,1982-04-06,10:43:00,91411,8.639,True,Human Resources
983,John,Male,1982-12-23,10:35:00,146907,11.738,False,Engineering
988,Alice,Female,2004-10-05,09:34:00,47638,11.209,False,Human Resources
992,Anthony,Male,2011-10-16,08:35:00,112769,11.625,True,Finance

## The duplicated Method
- The `duplicated` method returns True if a `Series` value is a duplicate.
- Pandas will mark one occurrence of a repeated value as a non-duplicate.
- Use the `keep` parameter to designate whether to consider the first or last occurrence of a repeated value as the non-duplicate.
- Pass `False` to the `keep` parameter to mark all occurrences of repeated values as duplicates.

In [37]:
employees = pd.read_csv("employees.csv").astype(
    {"Senior Management": bool, "Gender": "category", "Team": "category"}
)

employees["Start Date"] = pd.to_datetime(employees["Start Date"], format="%m/%d/%Y")
employees["Last Login Time"] = pd.to_datetime(
    employees["Last Login Time"], format="%H:%M %p"
).dt.time

employees.head()

,First Name,Gender,Start Date,Last Login Time,Salary,Bonus %,Senior Management,Team
0,Douglas,Male,1993-08-06,12:42:00,97308,6.945,True,Marketing
1,Thomas,Male,1996-03-31,06:53:00,61933,4.170,True,NaN
2,Maria,Female,1993-04-23,11:17:00,130590,11.858,False,Finance
3,Jerry,Male,2005-03-04,01:00:00,138705,9.340,True,Finance
4,Larry,Male,1998-01-24,04:47:00,101004,1.389,True,Client Services

In [38]:
employees[employees["First Name"] == "Larry"]

,First Name,Gender,Start Date,Last Login Time,Salary,Bonus %,Senior Management,Team
4,Larry,Male,1998-01-24,04:47:00,101004,1.389,True,Client Services
371,Larry,Male,2003-08-27,01:00:00,91133,5.140,False,Sales
515,Larry,Male,1999-01-08,02:05:00,97370,10.458,False,Sales
998,Larry,Male,2013-04-20,04:45:00,60500,11.985,False,Business Development

In [39]:
employees[employees["First Name"].duplicated()]
employees[employees["First Name"].duplicated(keep="first")]
employees[employees["First Name"].duplicated(keep="last")]
employees[employees["First Name"].duplicated(keep=False)]

,First Name,Gender,Start Date,Last Login Time,Salary,Bonus %,Senior Management,Team
0,Douglas,Male,1993-08-06,12:42:00,97308,6.945,True,Marketing
1,Thomas,Male,1996-03-31,06:53:00,61933,4.170,True,NaN
2,Maria,Female,1993-04-23,11:17:00,130590,11.858,False,Finance
3,Jerry,Male,2005-03-04,01:00:00,138705,9.340,True,Finance
4,Larry,Male,1998-01-24,04:47:00,101004,1.389,True,Client Services
...,...,...,...,...,...,...,...,...
995,Henry,NaN,2014-11-23,06:09:00,132483,16.655,False,Distribution
996,Phillip,Male,1984-01-31,06:30:00,42392,19.675,False,Finance
997,Russell,Male,2013-05-20,12:39:00,96914,1.421,False,Product
998,Larry,Male,2013-04-20,04:45:00,60500,11.985,False,Business Development
999,Albert,Male,2012-05-15,06:24:00,129949,10.169,True,Sales

- Use the tilde symbol (`~`) to invert a `Series's` values. True will become Falses, and Falses will become Trues.

In [40]:
employees[~employees["First Name"].duplicated(keep=False)]

,First Name,Gender,Start Date,Last Login Time,Salary,Bonus %,Senior Management,Team
5,Dennis,Male,1987-04-18,01:35:00,115163,10.125,False,Legal
8,Angela,Female,2005-11-22,06:29:00,95570,18.523,True,Engineering
33,Jean,Female,1993-12-18,09:07:00,119082,16.180,False,Business Development
190,Carol,Female,1996-03-19,03:39:00,57783,9.129,False,Finance
291,Tammy,Female,1984-11-11,10:30:00,132839,17.463,True,Client Services
495,Eugene,Male,1984-05-24,10:54:00,81077,2.117,False,Sales
688,Brian,Male,2007-04-07,10:47:00,93901,17.821,True,Legal
832,Keith,Male,2003-02-12,03:02:00,120672,19.467,False,Legal
887,David,Male,2009-12-05,08:48:00,92242,15.407,False,Legal

In [41]:
employees[employees["First Name"] == "Angela"]

,First Name,Gender,Start Date,Last Login Time,Salary,Bonus %,Senior Management,Team
8,Angela,Female,2005-11-22,06:29:00,95570,18.523,True,Engineering

## The drop_duplicates Method
- The `drop_duplicates` method deletes rows with duplicate values.
- By default, it will remove a row if *all* of its values are shared with another row.
- The `subset` parameter configures the columns to look for duplicate values within.

In [42]:
employees = pd.read_csv("employees.csv").astype(
    {"Senior Management": bool, "Gender": "category", "Team": "category"}
)

employees["Start Date"] = pd.to_datetime(employees["Start Date"], format="%m/%d/%Y")
employees["Last Login Time"] = pd.to_datetime(
    employees["Last Login Time"], format="%H:%M %p"
).dt.time

employees.head()

,First Name,Gender,Start Date,Last Login Time,Salary,Bonus %,Senior Management,Team
0,Douglas,Male,1993-08-06,12:42:00,97308,6.945,True,Marketing
1,Thomas,Male,1996-03-31,06:53:00,61933,4.170,True,NaN
2,Maria,Female,1993-04-23,11:17:00,130590,11.858,False,Finance
3,Jerry,Male,2005-03-04,01:00:00,138705,9.340,True,Finance
4,Larry,Male,1998-01-24,04:47:00,101004,1.389,True,Client Services

In [43]:
employees.drop_duplicates("Team")
employees.drop_duplicates("Team", keep="first")
employees.drop_duplicates("Team", keep="last")
employees.drop_duplicates("Team", keep=False)

employees.drop_duplicates("First Name", keep=False)

,First Name,Gender,Start Date,Last Login Time,Salary,Bonus %,Senior Management,Team
5,Dennis,Male,1987-04-18,01:35:00,115163,10.125,False,Legal
8,Angela,Female,2005-11-22,06:29:00,95570,18.523,True,Engineering
33,Jean,Female,1993-12-18,09:07:00,119082,16.180,False,Business Development
190,Carol,Female,1996-03-19,03:39:00,57783,9.129,False,Finance
291,Tammy,Female,1984-11-11,10:30:00,132839,17.463,True,Client Services
495,Eugene,Male,1984-05-24,10:54:00,81077,2.117,False,Sales
688,Brian,Male,2007-04-07,10:47:00,93901,17.821,True,Legal
832,Keith,Male,2003-02-12,03:02:00,120672,19.467,False,Legal
887,David,Male,2009-12-05,08:48:00,92242,15.407,False,Legal

- Pass a list to `subset` parameter to look for duplicates across multiple columns.

In [44]:
employees.drop_duplicates(["Senior Management", "Team"]).sort_values("Team")

employees.drop_duplicates(["Senior Management", "Team"], keep="last").sort_values(
    "Team"
)

,First Name,Gender,Start Date,Last Login Time,Salary,Bonus %,Senior Management,Team
971,Patrick,Male,2002-12-30,02:01:00,75423,5.368,True,Business Development
998,Larry,Male,2013-04-20,04:45:00,60500,11.985,False,Business Development
965,Catherine,Female,1989-09-25,01:31:00,68164,18.393,False,Client Services
990,Robin,Female,1987-07-24,01:35:00,100765,10.982,True,Client Services
946,NaN,Female,1985-09-15,01:50:00,133472,16.941,True,Distribution
995,Henry,NaN,2014-11-23,06:09:00,132483,16.655,False,Distribution
993,Tina,Female,1997-05-15,03:53:00,56450,19.040,True,Engineering
984,Maria,Female,2011-10-15,04:53:00,43455,13.040,False,Engineering
996,Phillip,Male,1984-01-31,06:30:00,42392,19.675,False,Finance
992,Anthony,Male,2011-10-16,08:35:00,112769,11.625,True,Finance
988,Alice,Female,2004-10-05,09:34:00,47638,11.209,False,Human Resources
982,Rose,Female,1982-04-06,10:43:00,91411,8.639,True,Human Resources
976,Denise,Female,1992-10-19,05:42:00,137954,4.195,True,Legal
989,Justin,NaN,1991-02-10,04:58:00,38344,3.794,False,Legal
986,Donna,Female,1982-11-26,07:04:00,82871,17.999,False,Marketing
994,George,Male,2013-06-21,05:47:00,98874,4.479,True,Marketing
979,Ernest,Male,2013-07-20,06:41:00,142935,13.198,True,Product
997,Russell,Male,2013-05-20,12:39:00,96914,1.421,False,Product
975,Susan,Female,1995-04-07,10:05:00,92436,12.467,False,Sales
999,Albert,Male,2012-05-15,06:24:00,129949,10.169,True,Sales
912,Joe,Male,1998-12-08,10:28:00,126120,1.020,False,NaN
951,NaN,Female,2010-09-14,05:19:00,143638,9.662,True,NaN

## The where Method
- Like the square brackets, the `where` method accepts a Boolean `Series` to filter the `DataFrame`.
- The resulting `DataFrame` will be of the same length as the original.
- Rows that do not satisfy the filtering criteria will have `NaN`s.
- The `where` method is ideal when you want to preserve the original `DataFrame` structure.

In [45]:
employees = pd.read_csv("employees.csv").astype(
    {"Senior Management": bool, "Gender": "category", "Team": "category"}
)

employees["Start Date"] = pd.to_datetime(employees["Start Date"], format="%m/%d/%Y")
employees["Last Login Time"] = pd.to_datetime(
    employees["Last Login Time"], format="%H:%M %p"
).dt.time

employees.head()

,First Name,Gender,Start Date,Last Login Time,Salary,Bonus %,Senior Management,Team
0,Douglas,Male,1993-08-06,12:42:00,97308,6.945,True,Marketing
1,Thomas,Male,1996-03-31,06:53:00,61933,4.170,True,NaN
2,Maria,Female,1993-04-23,11:17:00,130590,11.858,False,Finance
3,Jerry,Male,2005-03-04,01:00:00,138705,9.340,True,Finance
4,Larry,Male,1998-01-24,04:47:00,101004,1.389,True,Client Services

In [46]:
has_nice_salary = employees["Salary"] > 100000

In [47]:
employees.where(has_nice_salary)

,First Name,Gender,Start Date,Last Login Time,Salary,Bonus %,Senior Management,Team
0,NaN,NaN,NaT,NaN,NaN,NaN,NaN,NaN
1,NaN,NaN,NaT,NaN,NaN,NaN,NaN,NaN
2,Maria,Female,1993-04-23,11:17:00,130590.0,11.858,False,Finance
3,Jerry,Male,2005-03-04,01:00:00,138705.0,9.340,True,Finance
4,Larry,Male,1998-01-24,04:47:00,101004.0,1.389,True,Client Services
...,...,...,...,...,...,...,...,...
995,Henry,NaN,2014-11-23,06:09:00,132483.0,16.655,False,Distribution
996,NaN,NaN,NaT,NaN,NaN,NaN,NaN,NaN
997,NaN,NaN,NaT,NaN,NaN,NaN,NaN,NaN
998,NaN,NaN,NaT,NaN,NaN,NaN,NaN,NaN
999,Albert,Male,2012-05-15,06:24:00,129949.0,10.169,True,Sales

In [48]:
employees["Salary"] = employees["Salary"].where(has_nice_salary)

In [49]:
employees

,First Name,Gender,Start Date,Last Login Time,Salary,Bonus %,Senior Management,Team
0,Douglas,Male,1993-08-06,12:42:00,NaN,6.945,True,Marketing
1,Thomas,Male,1996-03-31,06:53:00,NaN,4.170,True,NaN
2,Maria,Female,1993-04-23,11:17:00,130590.0,11.858,False,Finance
3,Jerry,Male,2005-03-04,01:00:00,138705.0,9.340,True,Finance
4,Larry,Male,1998-01-24,04:47:00,101004.0,1.389,True,Client Services
...,...,...,...,...,...,...,...,...
995,Henry,NaN,2014-11-23,06:09:00,132483.0,16.655,False,Distribution
996,Phillip,Male,1984-01-31,06:30:00,NaN,19.675,False,Finance
997,Russell,Male,2013-05-20,12:39:00,NaN,1.421,False,Product
998,Larry,Male,2013-04-20,04:45:00,NaN,11.985,False,Business Development
999,Albert,Male,2012-05-15,06:24:00,129949.0,10.169,True,Sales

## The query Method
- The `query` method filters a `DataFrame` using a string argument.
- Its argument is a more readable alternative to Boolean filtering.

In [50]:
employees = pd.read_csv("employees.csv").astype(
    {"Senior Management": bool, "Gender": "category", "Team": "category"}
)

employees["Start Date"] = pd.to_datetime(employees["Start Date"], format="%m/%d/%Y")
employees["Last Login Time"] = pd.to_datetime(
    employees["Last Login Time"], format="%H:%M %p"
).dt.time

employees.head()

,First Name,Gender,Start Date,Last Login Time,Salary,Bonus %,Senior Management,Team
0,Douglas,Male,1993-08-06,12:42:00,97308,6.945,True,Marketing
1,Thomas,Male,1996-03-31,06:53:00,61933,4.170,True,NaN
2,Maria,Female,1993-04-23,11:17:00,130590,11.858,False,Finance
3,Jerry,Male,2005-03-04,01:00:00,138705,9.340,True,Finance
4,Larry,Male,1998-01-24,04:47:00,101004,1.389,True,Client Services

- Use `and`, `or`, and `not` (or `&`, `|`, `~`) within the expression string.

In [51]:
employees.query("Salary > 100000")

,First Name,Gender,Start Date,Last Login Time,Salary,Bonus %,Senior Management,Team
2,Maria,Female,1993-04-23,11:17:00,130590,11.858,False,Finance
3,Jerry,Male,2005-03-04,01:00:00,138705,9.340,True,Finance
4,Larry,Male,1998-01-24,04:47:00,101004,1.389,True,Client Services
5,Dennis,Male,1987-04-18,01:35:00,115163,10.125,False,Legal
9,Frances,Female,2002-08-08,06:51:00,139852,7.524,True,Business Development
...,...,...,...,...,...,...,...,...
990,Robin,Female,1987-07-24,01:35:00,100765,10.982,True,Client Services
991,Rose,Female,2002-08-25,05:12:00,134505,11.051,True,Marketing
992,Anthony,Male,2011-10-16,08:35:00,112769,11.625,True,Finance
995,Henry,NaN,2014-11-23,06:09:00,132483,16.655,False,Distribution
999,Albert,Male,2012-05-15,06:24:00,129949,10.169,True,Sales

In [52]:
employees.query("Gender == 'Female' and Team == 'Marketing'")
employees.query("Gender == 'Female' or Team == 'Marketing'")

,First Name,Gender,Start Date,Last Login Time,Salary,Bonus %,Senior Management,Team
0,Douglas,Male,1993-08-06,12:42:00,97308,6.945,True,Marketing
2,Maria,Female,1993-04-23,11:17:00,130590,11.858,False,Finance
6,Ruby,Female,1987-08-17,04:20:00,65476,10.012,True,Product
7,NaN,Female,2015-07-20,10:43:00,45906,11.598,True,Finance
8,Angela,Female,2005-11-22,06:29:00,95570,18.523,True,Engineering
...,...,...,...,...,...,...,...,...
988,Alice,Female,2004-10-05,09:34:00,47638,11.209,False,Human Resources
990,Robin,Female,1987-07-24,01:35:00,100765,10.982,True,Client Services
991,Rose,Female,2002-08-25,05:12:00,134505,11.051,True,Marketing
993,Tina,Female,1997-05-15,03:53:00,56450,19.040,True,Engineering
994,George,Male,2013-06-21,05:47:00,98874,4.479,True,Marketing

In [53]:
employees.query("60000 <= Salary <= 70000")

,First Name,Gender,Start Date,Last Login Time,Salary,Bonus %,Senior Management,Team
1,Thomas,Male,1996-03-31,06:53:00,61933,4.170,True,NaN
6,Ruby,Female,1987-08-17,04:20:00,65476,10.012,True,Product
10,Louise,Female,1980-08-12,09:01:00,63241,15.132,True,NaN
20,Lois,NaN,1995-04-22,07:18:00,64714,4.934,True,Legal
41,Christine,NaN,2015-06-28,01:08:00,66582,11.308,True,Business Development
...,...,...,...,...,...,...,...,...
965,Catherine,Female,1989-09-25,01:31:00,68164,18.393,False,Client Services
970,Alice,Female,1988-09-03,08:54:00,63571,15.397,True,Product
974,Harry,Male,2011-08-30,06:31:00,67656,16.455,True,Client Services
978,Sean,Male,1983-01-17,02:23:00,66146,11.178,False,Human Resources
998,Larry,Male,2013-04-20,04:45:00,60500,11.985,False,Business Development

- Use the `in` and `not in` operators to check inclusion/exclusion.

In [54]:
employees.query("Team in ['Legal', 'Sales', 'Product']")

employees.query("Team not in ['Legal', 'Sales', 'Product']")

,First Name,Gender,Start Date,Last Login Time,Salary,Bonus %,Senior Management,Team
0,Douglas,Male,1993-08-06,12:42:00,97308,6.945,True,Marketing
1,Thomas,Male,1996-03-31,06:53:00,61933,4.170,True,NaN
2,Maria,Female,1993-04-23,11:17:00,130590,11.858,False,Finance
3,Jerry,Male,2005-03-04,01:00:00,138705,9.340,True,Finance
4,Larry,Male,1998-01-24,04:47:00,101004,1.389,True,Client Services
...,...,...,...,...,...,...,...,...
993,Tina,Female,1997-05-15,03:53:00,56450,19.040,True,Engineering
994,George,Male,2013-06-21,05:47:00,98874,4.479,True,Marketing
995,Henry,NaN,2014-11-23,06:09:00,132483,16.655,False,Distribution
996,Phillip,Male,1984-01-31,06:30:00,42392,19.675,False,Finance
998,Larry,Male,2013-04-20,04:45:00,60500,11.985,False,Business Development

- Use the `@` prefix to reference local variables.

In [55]:
min_salary = 130000

In [56]:
employees.query("Salary > @min_salary")

,First Name,Gender,Start Date,Last Login Time,Salary,Bonus %,Senior Management,Team
2,Maria,Female,1993-04-23,11:17:00,130590,11.858,False,Finance
3,Jerry,Male,2005-03-04,01:00:00,138705,9.340,True,Finance
9,Frances,Female,2002-08-08,06:51:00,139852,7.524,True,Business Development
18,Diana,Female,1981-10-23,10:27:00,132940,19.082,False,Client Services
36,Rachel,Female,2009-02-16,08:47:00,142032,12.599,False,Business Development
...,...,...,...,...,...,...,...,...
981,James,Male,1993-01-15,05:19:00,148985,19.280,False,Legal
983,John,Male,1982-12-23,10:35:00,146907,11.738,False,Engineering
987,Gloria,Female,2014-12-08,05:08:00,136709,10.331,True,Finance
991,Rose,Female,2002-08-25,05:12:00,134505,11.051,True,Marketing
995,Henry,NaN,2014-11-23,06:09:00,132483,16.655,False,Distribution