# Merging DataFrames

In [1]:
import pandas as pd

## Our Datasets
- Our datasets are located in multiple files in the `library/` folder.
- The `books.csv` file stores the library's book catalog.
- The `members.csv` file stores the library's registered members.
- The `checkouts_jan` and `checkouts_feb` files stores borrowing records from January and February.

In [2]:
books = pd.read_csv("library/books.csv")
books.head()

   Book ID                    Title               Author        Genre
0        1    To Kill a Mockingbird           Harper Lee      Fiction
1        2                     1984        George Orwell      Fiction
2        3  A Brief History of Time      Stephen Hawking      Science
3        4         The Great Gatsby  F. Scott Fitzgerald      Fiction
4        5             Freakonomics        Steven Levitt  Non-Fiction

In [3]:
members = pd.read_csv("library/members.csv", parse_dates=["Signup Date"])
members.head()

,ID,First Name,Last Name,Email,Membership,Signup Date
0,1,Samantha,Anderson,samantha.anderson4@outlook.com,Basic,2020-10-12
1,2,Jack,Wilson,jack.wilson87@proton.me,Basic,2022-05-14
2,3,John,Brown,john.brown12@yahoo.com,Basic,2023-05-17
3,4,Patricia,Bailey,patricia.bailey26@proton.me,Basic,2022-07-08
4,5,Emma,Scott,emma.scott1@yahoo.com,Premium,2021-11-27

In [4]:
jan = pd.read_csv("library/checkouts_jan.csv")
feb = pd.read_csv("library/checkouts_feb.csv")
feb.head()

      Branch  Member ID  Book ID
0  Riverside         80        3
1   Eastgate        753       33
2   Downtown         39       19
3   Westside        300       30
4   Eastgate          5       13

In [5]:
books = pd.read_csv("library/books.csv")
members = pd.read_csv("library/members.csv", parse_dates=["Signup Date"])
jan = pd.read_csv("library/checkouts_jan.csv")
feb = pd.read_csv("library/checkouts_feb.csv")

## The pd.concat Function I
- The `concat` function concatenates one `DataFrame` to the end of another.
- The original index labels will be kept by default. Set `ignore_index` to `True` to generate a new index.

In [6]:
books = pd.read_csv("library/books.csv")
members = pd.read_csv("library/members.csv", parse_dates=["Signup Date"])
jan = pd.read_csv("library/checkouts_jan.csv")
feb = pd.read_csv("library/checkouts_feb.csv")

In [7]:
jan.head(2)

      Branch  Member ID  Book ID
0   Westside        587        5
1  Northpark        158       25

In [8]:
feb.head(2)

      Branch  Member ID  Book ID
0  Riverside         80        3
1   Eastgate        753       33

In [9]:
len(jan)
len(feb)

250

In [10]:
pd.concat([jan, feb])
pd.concat([jan, feb], ignore_index=False)
pd.concat([jan, feb], ignore_index=True)

        Branch  Member ID  Book ID
0     Westside        587        5
1    Northpark        158       25
2     Downtown        820       23
3     Downtown        800       29
4    Northpark        150       19
..         ...        ...      ...
495   Westside        616       16
496   Downtown         62       20
497  Riverside        502       35
498   Westside        484       17
499  Riverside        468       32

[500 rows x 3 columns]

- The `keys` parameter creates a `MultiIndex` using the specified keys/labels.

In [11]:
pd.concat([jan, feb], keys=["January", "February"])

                 Branch  Member ID  Book ID
January  0     Westside        587        5
         1    Northpark        158       25
         2     Downtown        820       23
         3     Downtown        800       29
         4    Northpark        150       19
...                 ...        ...      ...
February 245   Westside        616       16
         246   Downtown         62       20
         247  Riverside        502       35
         248   Westside        484       17
         249  Riverside        468       32

[500 rows x 3 columns]

## The pd.concat Function II
- Pandas concatenates the `DataFrame` objects along the row/index axis by default.
- Pandas will include all columns that exist in either `DataFrame`. If there are no matching values, pandas will use `NaN` values.
- Pass the `axis` parameter an argument of `"columns"` to concatenate on the column axis.

In [12]:
books = pd.read_csv("library/books.csv")
members = pd.read_csv("library/members.csv", parse_dates=["Signup Date"])
jan = pd.read_csv("library/checkouts_jan.csv")
feb = pd.read_csv("library/checkouts_feb.csv")

In [13]:
titles = books["Title"].to_frame()
titles.head()

                     Title
0    To Kill a Mockingbird
1                     1984
2  A Brief History of Time
3         The Great Gatsby
4             Freakonomics

In [14]:
authors = books["Author"].to_frame()
authors.head()

                Author
0           Harper Lee
1        George Orwell
2      Stephen Hawking
3  F. Scott Fitzgerald
4        Steven Levitt

In [15]:
pd.concat([titles, authors])
# pd.concat([titles, authors], axis="index")
pd.concat([titles, authors], axis="columns")

                                    Title                  Author
0                   To Kill a Mockingbird              Harper Lee
1                                    1984           George Orwell
2                 A Brief History of Time         Stephen Hawking
3                        The Great Gatsby     F. Scott Fitzgerald
4                            Freakonomics           Steven Levitt
5                                    Dune           Frank Herbert
6                                Educated           Tara Westover
7                              The Hobbit          J.R.R. Tolkien
8                     Pride and Prejudice             Jane Austen
9                              Clean Code        Robert C. Martin
10                 The Catcher in the Rye           J.D. Salinger
11                        Brave New World           Aldous Huxley
12                          The Alchemist            Paulo Coelho
13  Harry Potter and the Sorcerer's Stone            J.K. Rowling
14                  The Lord of the Rings          J.R.R. Tolkien
15                              Jane Eyre        Charlotte Bronte
16                      Wuthering Heights            Emily Bronte
17             The Picture of Dorian Gray             Oscar Wilde
18                         Fahrenheit 451            Ray Bradbury
19                                 Cosmos              Carl Sagan
20                 Thinking Fast and Slow         Daniel Kahneman
21                      The Da Vinci Code               Dan Brown
22                              Gone Girl           Gillian Flynn
23                            The Martian               Andy Weir
24                          Atomic Habits             James Clear
25                               Outliers        Malcolm Gladwell
26          The Design of Everyday Things              Don Norman
27                           Ender's Game        Orson Scott Card
28                           Little Women       Louisa May Alcott
29                        Treasure Island  Robert Louis Stevenson
30                           Frankenstein            Mary Shelley
31                                Dracula             Bram Stoker
32                     The Silent Patient        Alex Michaelides
33                      Project Hail Mary               Andy Weir
34   A Short History of Nearly Everything             Bill Bryson

In [16]:
books = pd.read_csv("library/books.csv", index_col="Title")
books.head()

                         Book ID               Author        Genre
Title
To Kill a Mockingbird          1           Harper Lee      Fiction
1984                           2        George Orwell      Fiction
A Brief History of Time        3      Stephen Hawking      Science
The Great Gatsby               4  F. Scott Fitzgerald      Fiction
Freakonomics                   5        Steven Levitt  Non-Fiction

In [17]:
first = books[["Book ID", "Author"]].sort_index()
first.head(3)

                                      Book ID           Author
Title
1984                                        2    George Orwell
A Brief History of Time                     3  Stephen Hawking
A Short History of Nearly Everything       35      Bill Bryson

In [18]:
second = books[["Genre"]]
second.head(3)

                           Genre
Title
To Kill a Mockingbird    Fiction
1984                     Fiction
A Brief History of Time  Science

In [19]:
pd.concat([first, second], axis="columns")

,Book ID,Author,Genre
Title,,,
1984,2,George Orwell,Fiction
A Brief History of Time,3,Stephen Hawking,Science
A Short History of Nearly Everything,35,Bill Bryson,Science
Atomic Habits,25,James Clear,Non-Fiction
Brave New World,12,Aldous Huxley,Fiction
Clean Code,10,Robert C. Martin,Technology
Cosmos,20,Carl Sagan,Science
Dracula,32,Bram Stoker,Fiction
Dune,6,Frank Herbert,Sci-Fi
Educated,7,Tara Westover,Memoir
Ender's Game,28,Orson Scott Card,Sci-Fi
Fahrenheit 451,19,Ray Bradbury,Sci-Fi
Frankenstein,31,Mary Shelley,Fiction
Freakonomics,5,Steven Levitt,Non-Fiction
Gone Girl,23,Gillian Flynn,Fiction
Harry Potter and the Sorcerer's Stone,14,J.K. Rowling,Fiction
Jane Eyre,16,Charlotte Bronte,Fiction
Little Women,29,Louisa May Alcott,Fiction
Outliers,26,Malcolm Gladwell,Non-Fiction
Pride and Prejudice,9,Jane Austen,Fiction
Project Hail Mary,34,Andy Weir,Sci-Fi
The Alchemist,13,Paulo Coelho,Fiction
The Catcher in the Rye,11,J.D. Salinger,Fiction
The Da Vinci Code,22,Dan Brown,Fiction
The Design of Everyday Things,27,Don Norman,Technology
The Great Gatsby,4,F. Scott Fitzgerald,Fiction
The Hobbit,8,J.R.R. Tolkien,Fiction
The Lord of the Rings,15,J.R.R. Tolkien,Fiction
The Martian,24,Andy Weir,Sci-Fi
The Picture of Dorian Gray,18,Oscar Wilde,Fiction
The Silent Patient,33,Alex Michaelides,Fiction
Thinking Fast and Slow,21,Daniel Kahneman,Non-Fiction
To Kill a Mockingbird,1,Harper Lee,Fiction
Treasure Island,30,Robert Louis Stevenson,Fiction
Wuthering Heights,17,Emily Bronte,Fiction

## Left Joins
- The `merge` method joins two `DataFrame` objects together based on shared values in a column or an index.
- A left join merges one `DataFrame` into another based on values in the first one.
- The "left" `DataFrame` is the one we invoke the `merge` method on.
- If the left `DataFrame`'s value is not found in the right `DataFrame`, the row will hold `NaN` values.
<img src="assets/SQL_Joins.png" width="800" height="800"/>

In [20]:
books = pd.read_csv("library/books.csv")
members = pd.read_csv("library/members.csv", parse_dates=["Signup Date"])
jan = pd.read_csv("library/checkouts_jan.csv")
feb = pd.read_csv("library/checkouts_feb.csv")

In [21]:
jan.head()

      Branch  Member ID  Book ID
0   Westside        587        5
1  Northpark        158       25
2   Downtown        820       23
3   Downtown        800       29
4  Northpark        150       19

In [22]:
books.head()

   Book ID                    Title               Author        Genre
0        1    To Kill a Mockingbird           Harper Lee      Fiction
1        2                     1984        George Orwell      Fiction
2        3  A Brief History of Time      Stephen Hawking      Science
3        4         The Great Gatsby  F. Scott Fitzgerald      Fiction
4        5             Freakonomics        Steven Levitt  Non-Fiction

In [23]:
jan.merge(books, how="left", on="Book ID")

,Branch,Member ID,Book ID,Title,Author,Genre
0,Westside,587,5,Freakonomics,Steven Levitt,Non-Fiction
1,Northpark,158,25,Atomic Habits,James Clear,Non-Fiction
2,Downtown,820,23,Gone Girl,Gillian Flynn,Fiction
3,Downtown,800,29,Little Women,Louisa May Alcott,Fiction
4,Northpark,150,19,Fahrenheit 451,Ray Bradbury,Sci-Fi
...,...,...,...,...,...,...
245,Eastgate,491,4,The Great Gatsby,F. Scott Fitzgerald,Fiction
246,Riverside,196,25,Atomic Habits,James Clear,Non-Fiction
247,Downtown,770,7,Educated,Tara Westover,Memoir
248,Westside,770,7,Educated,Tara Westover,Memoir
249,Northpark,312,28,Ender's Game,Orson Scott Card,Sci-Fi

## The left_on and right_on Parameters
- The `left_on` and `right_on` parameters designate the column names from each `DataFrame` to use in the merge.

In [24]:
books = pd.read_csv("library/books.csv")
members = pd.read_csv("library/members.csv", parse_dates=["Signup Date"])
jan = pd.read_csv("library/checkouts_jan.csv")
feb = pd.read_csv("library/checkouts_feb.csv")

In [25]:
jan.merge(books, how="left", on="Book ID")

,Branch,Member ID,Book ID,Title,Author,Genre
0,Westside,587,5,Freakonomics,Steven Levitt,Non-Fiction
1,Northpark,158,25,Atomic Habits,James Clear,Non-Fiction
2,Downtown,820,23,Gone Girl,Gillian Flynn,Fiction
3,Downtown,800,29,Little Women,Louisa May Alcott,Fiction
4,Northpark,150,19,Fahrenheit 451,Ray Bradbury,Sci-Fi
...,...,...,...,...,...,...
245,Eastgate,491,4,The Great Gatsby,F. Scott Fitzgerald,Fiction
246,Riverside,196,25,Atomic Habits,James Clear,Non-Fiction
247,Downtown,770,7,Educated,Tara Westover,Memoir
248,Westside,770,7,Educated,Tara Westover,Memoir
249,Northpark,312,28,Ender's Game,Orson Scott Card,Sci-Fi

In [26]:
jan.merge(members, how="left", left_on="Member ID", right_on="ID").drop(columns=["ID"])

,Branch,Member ID,Book ID,First Name,Last Name,Email,Membership,Signup Date
0,Westside,587,5,Alexander,Ward,alexander.ward81@icloud.com,Basic,2020-10-12
1,Northpark,158,25,Nicole,Kim,nicole.kim80@yahoo.com,Student,2022-02-18
2,Downtown,820,23,Kathleen,Hall,kathleen.hall85@icloud.com,Basic,2024-08-19
3,Downtown,800,29,Heather,King,heather.king67@yahoo.com,Basic,2022-04-19
4,Northpark,150,19,Matthew,Nguyen,matthew.nguyen30@outlook.com,Basic,2020-01-29
...,...,...,...,...,...,...,...,...
245,Eastgate,491,4,Mark,Patel,mark.patel19@gmail.com,Basic,2023-04-11
246,Riverside,196,25,Timothy,Roberts,timothy.roberts85@yahoo.com,Premium,2020-03-16
247,Downtown,770,7,Lisa,James,lisa.james72@yahoo.com,Basic,2022-08-22
248,Westside,770,7,Lisa,James,lisa.james72@yahoo.com,Basic,2022-08-22
249,Northpark,312,28,Jack,Ortiz,jack.ortiz5@outlook.com,Student,2023-06-19

## Inner Joins I
- Inner joins merge two tables based on *shared*/*common* values in columns.
- If only one `DataFrame` has a value, pandas will exclude it from the final results set.
- If the same ID occurs multiple times, pandas will store each possible combination of the values.
- The design of the join ensures that the results will be the same no matter what `DataFrame` the `merge` method is invoked upon.
<img src="assets/SQL_Joins.png" width="800" height="800"/>

In [27]:
books = pd.read_csv("library/books.csv")
members = pd.read_csv("library/members.csv", parse_dates=["Signup Date"])
jan = pd.read_csv("library/checkouts_jan.csv")
feb = pd.read_csv("library/checkouts_feb.csv")

- Let's identify the members who checked out a book in both January and February.

In [28]:
jan.head()

      Branch  Member ID  Book ID
0   Westside        587        5
1  Northpark        158       25
2   Downtown        820       23
3   Downtown        800       29
4  Northpark        150       19

In [29]:
feb.head()

      Branch  Member ID  Book ID
0  Riverside         80        3
1   Eastgate        753       33
2   Downtown         39       19
3   Westside        300       30
4   Eastgate          5       13

In [30]:
jan.merge(feb, how="inner", on="Member ID")
jan.merge(feb, how="inner", on="Member ID", suffixes=[" - Jan", " - Feb"])

    Branch - Jan  Member ID  Book ID - Jan Branch - Feb  Book ID - Feb
0       Westside        587              5     Eastgate             34
1      Northpark        150             19     Eastgate             18
2      Northpark        150             19     Westside             18
3       Eastgate        178             10    Riverside             20
4       Eastgate        178             10    Northpark             11
..           ...        ...            ...          ...            ...
163    Northpark        201             14    Northpark             22
164    Riverside        587             17     Eastgate             34
165     Eastgate        925              9     Westside             29
166    Northpark        351              6    Northpark             30
167    Northpark        351              6     Downtown             29

[168 rows x 5 columns]

In [31]:
jan[jan["Member ID"] == 178]

     Branch  Member ID  Book ID
7  Eastgate        178       10

In [32]:
feb[feb["Member ID"] == 178]

        Branch  Member ID  Book ID
170  Riverside        178       20
233  Northpark        178       11

## Matching across Multiple Columns
- We can pass a list of multiple columns to the `on` parameter of the `merge` method.
- Pandas will require matching values in both columns across the two `DataFrames`.

In [33]:
books = pd.read_csv("library/books.csv")
members = pd.read_csv("library/members.csv", parse_dates=["Signup Date"])
jan = pd.read_csv("library/checkouts_jan.csv")
feb = pd.read_csv("library/checkouts_feb.csv")

- Let's identify the members who checked out the _same_ in book January and February.

In [34]:
jan.merge(feb, how="inner", on=["Member ID", "Book ID"])

    Branch_x  Member ID  Book ID   Branch_y
0   Eastgate        896        5  Riverside
1  Northpark         17       27  Riverside
2   Downtown         34       17   Eastgate
3   Eastgate        299       27  Northpark
4   Westside         29       35   Eastgate

In [35]:
condition_one = jan["Member ID"] == 896
condition_two = jan["Book ID"] == 5
jan[condition_one & condition_two]

     Branch  Member ID  Book ID
8  Eastgate        896        5

In [36]:
condition_one = feb["Member ID"] == 896
condition_two = feb["Book ID"] == 5
feb[condition_one & condition_two]

       Branch  Member ID  Book ID
57  Riverside        896        5

## Full/Outer Join
- A **full/outer** join includes values that are found in either `DataFrame` or both `DataFrame` objects.
- Pandas does not mind if a value exists in one `DataFrame` but not the other.
- If a value does not exist in one `DataFrame`, it will have a `NaN`.

<img src="assets/SQL_Joins.png" width="800" height="800"/>

In [37]:
books = pd.read_csv("library/books.csv")
members = pd.read_csv("library/members.csv", parse_dates=["Signup Date"])
jan = pd.read_csv("library/checkouts_jan.csv")
feb = pd.read_csv("library/checkouts_feb.csv")

In [38]:
jan.merge(feb, how="outer", on="Member ID", suffixes=[" - Jan", " - Feb"])
merged = jan.merge(
    feb, how="outer", on="Member ID", suffixes=[" - Jan", " - Feb"], indicator=True
)
merged.head()

,Branch - Jan,Member ID,Book ID - Jan,Branch - Feb,Book ID - Feb,_merge
0,NaN,2,NaN,Eastgate,19.0,right_only
1,NaN,5,NaN,Eastgate,13.0,right_only
2,NaN,5,NaN,Riverside,10.0,right_only
3,NaN,5,NaN,Westside,21.0,right_only
4,NaN,5,NaN,Northpark,16.0,right_only

In [39]:
merged["_merge"].value_counts()

_merge
both          168
left_only     151
right_only    149
Name: count, dtype: int64

In [40]:
merged[merged["_merge"] == "both"]
merged[merged["_merge"] == "left_only"]
merged[merged["_merge"] == "right_only"]

,Branch - Jan,Member ID,Book ID - Jan,Branch - Feb,Book ID - Feb,_merge
0,NaN,2,NaN,Eastgate,19.0,right_only
1,NaN,5,NaN,Eastgate,13.0,right_only
2,NaN,5,NaN,Riverside,10.0,right_only
3,NaN,5,NaN,Westside,21.0,right_only
4,NaN,5,NaN,Northpark,16.0,right_only
...,...,...,...,...,...,...
452,NaN,945,NaN,Eastgate,21.0,right_only
463,NaN,962,NaN,Eastgate,11.0,right_only
464,NaN,966,NaN,Eastgate,9.0,right_only
465,NaN,982,NaN,Eastgate,17.0,right_only
466,NaN,982,NaN,Eastgate,22.0,right_only

In [41]:
merged[merged["_merge"].isin(["left_only", "right_only"])]

,Branch - Jan,Member ID,Book ID - Jan,Branch - Feb,Book ID - Feb,_merge
0,NaN,2,NaN,Eastgate,19.0,right_only
1,NaN,5,NaN,Eastgate,13.0,right_only
2,NaN,5,NaN,Riverside,10.0,right_only
3,NaN,5,NaN,Westside,21.0,right_only
4,NaN,5,NaN,Northpark,16.0,right_only
...,...,...,...,...,...,...
463,NaN,962,NaN,Eastgate,11.0,right_only
464,NaN,966,NaN,Eastgate,9.0,right_only
465,NaN,982,NaN,Eastgate,17.0,right_only
466,NaN,982,NaN,Eastgate,22.0,right_only
467,Downtown,992,29.0,NaN,NaN,left_only

## Merging by Indexes with the left_index and right_index Parameters
- Use the `on` parameter if the column(s) to be matched on have the same names in both `DataFrame` objects.
- Use the `left_on` and `right_on` parameters if the columns with matches have different names.
- Use the `left_index` or `right_index` parameters (set to `True`) if the values to be matched are found in a `DataFrame` index.

In [42]:
books = pd.read_csv("library/books.csv", index_col="Book ID")
members = pd.read_csv(
    "library/members.csv", parse_dates=["Signup Date"], index_col="ID"
)
jan = pd.read_csv("library/checkouts_jan.csv")
feb = pd.read_csv("library/checkouts_feb.csv")

In [43]:
books.head(2)

                         Title         Author    Genre
Book ID
1        To Kill a Mockingbird     Harper Lee  Fiction
2                         1984  George Orwell  Fiction

In [44]:
members.head(2)

   First Name Last Name                           Email Membership Signup Date
ID
1    Samantha  Anderson  samantha.anderson4@outlook.com      Basic  2020-10-12
2        Jack    Wilson         jack.wilson87@proton.me      Basic  2022-05-14

In [45]:
jan.merge(members, how="left", left_on="Member ID", right_index=True).merge(
    books, how="left", left_on="Book ID", right_index=True
)

,Branch,Member ID,Book ID,First Name,Last Name,Email,Membership,Signup Date,Title,Author,Genre
0,Westside,587,5,Alexander,Ward,alexander.ward81@icloud.com,Basic,2020-10-12,Freakonomics,Steven Levitt,Non-Fiction
1,Northpark,158,25,Nicole,Kim,nicole.kim80@yahoo.com,Student,2022-02-18,Atomic Habits,James Clear,Non-Fiction
2,Downtown,820,23,Kathleen,Hall,kathleen.hall85@icloud.com,Basic,2024-08-19,Gone Girl,Gillian Flynn,Fiction
3,Downtown,800,29,Heather,King,heather.king67@yahoo.com,Basic,2022-04-19,Little Women,Louisa May Alcott,Fiction
4,Northpark,150,19,Matthew,Nguyen,matthew.nguyen30@outlook.com,Basic,2020-01-29,Fahrenheit 451,Ray Bradbury,Sci-Fi
...,...,...,...,...,...,...,...,...,...,...,...
245,Eastgate,491,4,Mark,Patel,mark.patel19@gmail.com,Basic,2023-04-11,The Great Gatsby,F. Scott Fitzgerald,Fiction
246,Riverside,196,25,Timothy,Roberts,timothy.roberts85@yahoo.com,Premium,2020-03-16,Atomic Habits,James Clear,Non-Fiction
247,Downtown,770,7,Lisa,James,lisa.james72@yahoo.com,Basic,2022-08-22,Educated,Tara Westover,Memoir
248,Westside,770,7,Lisa,James,lisa.james72@yahoo.com,Basic,2022-08-22,Educated,Tara Westover,Memoir
249,Northpark,312,28,Jack,Ortiz,jack.ortiz5@outlook.com,Student,2023-06-19,Ender's Game,Orson Scott Card,Sci-Fi

## The join Method
- The `join` method is a shortcut for joining two `DataFrames` using index labels.

In [46]:
books = pd.read_csv("library/books.csv")
members = pd.read_csv(
    "library/members.csv", parse_dates=["Signup Date"], index_col="ID"
).sort_index()
jan = pd.read_csv("library/checkouts_jan.csv", index_col="Member ID")
feb = pd.read_csv("library/checkouts_feb.csv")

In [47]:
jan.head(2)

              Branch  Book ID
Member ID
587         Westside        5
158        Northpark       25

In [48]:
members.head(2)

   First Name Last Name                           Email Membership Signup Date
ID
1    Samantha  Anderson  samantha.anderson4@outlook.com      Basic  2020-10-12
2        Jack    Wilson         jack.wilson87@proton.me      Basic  2022-05-14

In [49]:
jan.merge(members, how="left", left_index=True, right_index=True)

,Branch,Book ID,First Name,Last Name,Email,Membership,Signup Date
Member ID,,,,,,,
587,Westside,5,Alexander,Ward,alexander.ward81@icloud.com,Basic,2020-10-12
158,Northpark,25,Nicole,Kim,nicole.kim80@yahoo.com,Student,2022-02-18
820,Downtown,23,Kathleen,Hall,kathleen.hall85@icloud.com,Basic,2024-08-19
800,Downtown,29,Heather,King,heather.king67@yahoo.com,Basic,2022-04-19
150,Northpark,19,Matthew,Nguyen,matthew.nguyen30@outlook.com,Basic,2020-01-29
...,...,...,...,...,...,...,...
491,Eastgate,4,Mark,Patel,mark.patel19@gmail.com,Basic,2023-04-11
196,Riverside,25,Timothy,Roberts,timothy.roberts85@yahoo.com,Premium,2020-03-16
770,Downtown,7,Lisa,James,lisa.james72@yahoo.com,Basic,2022-08-22
770,Westside,7,Lisa,James,lisa.james72@yahoo.com,Basic,2022-08-22
312,Northpark,28,Jack,Ortiz,jack.ortiz5@outlook.com,Student,2023-06-19

In [50]:
jan.join(members)

,Branch,Book ID,First Name,Last Name,Email,Membership,Signup Date
Member ID,,,,,,,
587,Westside,5,Alexander,Ward,alexander.ward81@icloud.com,Basic,2020-10-12
158,Northpark,25,Nicole,Kim,nicole.kim80@yahoo.com,Student,2022-02-18
820,Downtown,23,Kathleen,Hall,kathleen.hall85@icloud.com,Basic,2024-08-19
800,Downtown,29,Heather,King,heather.king67@yahoo.com,Basic,2022-04-19
150,Northpark,19,Matthew,Nguyen,matthew.nguyen30@outlook.com,Basic,2020-01-29
...,...,...,...,...,...,...,...
491,Eastgate,4,Mark,Patel,mark.patel19@gmail.com,Basic,2023-04-11
196,Riverside,25,Timothy,Roberts,timothy.roberts85@yahoo.com,Premium,2020-03-16
770,Downtown,7,Lisa,James,lisa.james72@yahoo.com,Basic,2022-08-22
770,Westside,7,Lisa,James,lisa.james72@yahoo.com,Basic,2022-08-22
312,Northpark,28,Jack,Ortiz,jack.ortiz5@outlook.com,Student,2023-06-19