# Working with Dates and Times

In [1]:
import pandas as pd

## Review of Python's datetime Module
- A module is a file of Python code.
- The `datetime` module is part of Python's standard library, a collection of built-in features.
- The common alias for the `datetime` module is `dt`.

In [2]:
import datetime as dt

- The `datetime` module exports `date`, `time`, and `datetime` classes for representing dates and datetimes.
- The `date` constructor accepts arguments for year, month, and day.
- The `time` constructor accepts arguments for hours, minutes, and seconds.
- The `datetime` constructor accepts arguments for year, month, day, hour, minute, and second.
- The constructors default to 0 for any missing values.

In [3]:
someday = dt.date(2026, 12, 15)
type(someday)

datetime.date

In [4]:
someday.year
someday.month
someday.day

15

In [5]:
sometime = dt.time(8, 30, 45)
type(sometime)

datetime.time

In [6]:
sometime.hour
sometime.minute
sometime.second

45

In [7]:
dt.datetime(2026, 12, 15)
dt.datetime(2026, 12, 15, 8)
dt.datetime(2026, 12, 15, 8, 13)
sometime = dt.datetime(2026, 12, 15, 8, 13, 59)
type(sometime)

datetime.datetime

In [8]:
sometime.year
sometime.month
sometime.day
sometime.hour
sometime.minute
sometime.second

59

## The dt Attribute
- The `dt` attribute on a `Series` exposes a `DatetimeProperties` object with attributes/methods for working with datetimes.
- The `DatetimeProperties` object has attributes like `day`, `month`, and `year` to reveal information about each date in the `Series`.

In [9]:
stocks = pd.read_csv("ibm.csv", parse_dates=["Date"])
stocks.head()

        Date  Open  High   Low  Close  Volume
0 1962-01-02  1.48  1.48  1.46   1.46  407940
1 1962-01-03  1.46  1.48  1.46   1.48  305955
2 1962-01-04  1.48  1.48  1.46   1.46  274575
3 1962-01-05  1.46  1.46  1.43   1.43  384405
4 1962-01-08  1.43  1.43  1.39   1.41  572685

In [10]:
stocks["Date"].dt

In [11]:
stocks["Date"].dt.day
stocks["Date"].dt.month
stocks["Date"].dt.year
stocks["Date"].dt.day_of_year

0         2
1         3
2         4
3         5
4         8
         ..
16123    26
16124    27
16125    28
16126    29
16127    30
Name: Date, Length: 16128, dtype: int32

- The `day_name` method returns the written day of the week.

In [12]:
stocks["Date"].dt.day_name()

0          Tuesday
1        Wednesday
2         Thursday
3           Friday
4           Monday
           ...
16123       Monday
16124      Tuesday
16125    Wednesday
16126     Thursday
16127       Friday
Name: Date, Length: 16128, dtype: str

- Attributes like `is_month_end` and `is_quarter_start` return Boolean `Series`.

In [13]:
stocks[stocks["Date"].dt.is_month_end]

stocks[stocks["Date"].dt.is_quarter_start]

            Date    Open    High     Low   Close   Volume
189   1962-10-01    0.91    0.91    0.87    0.87  1937715
314   1963-04-01    1.08    1.08    1.08    1.08   713895
377   1963-07-01    1.12    1.12    1.09    1.09  1561155
441   1963-10-01    1.16    1.17    1.15    1.15   674670
565   1964-04-01    1.53    1.53    1.53    1.53   753120
...          ...     ...     ...     ...     ...      ...
15730 2024-07-01  166.30  169.19  166.24  167.89  3321000
15794 2024-10-01  213.39  213.85  208.82  212.15  3548400
15918 2025-04-01  243.39  245.94  238.94  245.66  4412900
15980 2025-07-01  290.97  291.52  286.55  287.66  3272800
16044 2025-10-01  278.66  285.02  278.61  284.92  4381300

[135 rows x 6 columns]

## The Timestamp Type
- Pandas has its own `Timestamp` type for modelling a date or datetime.

In [14]:
stocks = pd.read_csv("ibm.csv", parse_dates=["Date"])
stocks.head()

        Date  Open  High   Low  Close  Volume
0 1962-01-02  1.48  1.48  1.46   1.46  407940
1 1962-01-03  1.46  1.48  1.46   1.48  305955
2 1962-01-04  1.48  1.48  1.46   1.46  274575
3 1962-01-05  1.46  1.46  1.43   1.43  384405
4 1962-01-08  1.43  1.43  1.39   1.41  572685

In [15]:
pd.Timestamp(2026, 12, 15)
timestamp = pd.Timestamp(2026, 12, 15, 8, 30, 5)
timestamp.year

2026

- The `Timestamp` constructor also accepts `dt.date` and `dt.datetime` objects.
- The `Timestamp` cannot model a time without a day and thus does not accept `dt.time` objects.

In [16]:
pd.Timestamp(dt.date(2026, 12, 15))
pd.Timestamp(dt.datetime(2026, 12, 15, 8, 30, 5))
# pd.Timestamp(dt.time(8, 30))

Timestamp('2026-12-15 08:30:05')

- When we convert a column to `datetime64`, each row actually stores a `Timestamp`.

In [17]:
stocks["Date"].iloc[0]

Timestamp('1962-01-02 00:00:00')

## Extracting Datetime Rows from a DataFrame
- When generating a Boolean `Series` against a `datetime64` column, you can use either strings, `datetime` objects, or `Timestamp` objects.

In [18]:
stocks = pd.read_csv("ibm.csv", parse_dates=["Date"]).sort_values("Date")
stocks.head()

        Date  Open  High   Low  Close  Volume
0 1962-01-02  1.48  1.48  1.46   1.46  407940
1 1962-01-03  1.46  1.48  1.46   1.48  305955
2 1962-01-04  1.48  1.48  1.46   1.46  274575
3 1962-01-05  1.46  1.46  1.43   1.43  384405
4 1962-01-08  1.43  1.43  1.39   1.41  572685

In [19]:
stocks[stocks["Date"] == "1995-04-03"]
stocks[stocks["Date"] == "1995"]

stocks[stocks["Date"] == dt.datetime(1995, 4, 3)]
stocks[stocks["Date"] == pd.Timestamp(1995, 4, 3)]

stocks[stocks["Date"] == pd.Timestamp(dt.date(1995, 4, 3))]

stocks[stocks["Date"].between("1995-04-03", "1995-04-11")]

           Date   Open   High    Low  Close    Volume
8369 1995-04-03   9.79   9.93   9.79   9.86   7924914
8370 1995-04-04   9.89   9.95   9.82   9.87   7048366
8371 1995-04-05   9.86  10.01   9.86   9.99   8402727
8372 1995-04-06  10.04  10.07   9.95   9.98   6219516
8373 1995-04-07   9.96  10.13   9.93   9.99  10160007
8374 1995-04-10   9.99  10.23   9.99  10.23   8851670
8375 1995-04-11  10.22  10.34  10.19  10.32  10798904

- We can set a column of `datetime` values as the index.
- The `DataFrame` sill store a `DatetimeIndex` object.

In [20]:
stocks = pd.read_csv("ibm.csv", parse_dates=["Date"], index_col="Date").sort_index()
stocks.tail()

              Open    High     Low   Close    Volume
Date
2026-01-26  293.16  296.82  293.14  296.33   3726900
2026-01-27  297.16  297.33  293.27  293.86   2954900
2026-01-28  294.17  295.95  291.26  294.16   5790300
2026-01-29  317.86  319.90  303.47  309.24  10124900
2026-01-30  307.60  307.78  299.73  306.70   5938900

In [21]:
stocks.index[0]

Timestamp('1962-01-02 00:00:00')

- Use the `iloc` accessor for index position-based extraction.

In [22]:
stocks.iloc[5]

Open           1.41
High           1.44
Low            1.41
Close          1.42
Volume    517770.00
Name: 1962-01-09 00:00:00, dtype: float64

- Use the `loc` accessor for index label-based extraction.
- The accessor accepts strings, `datetime` objects, or `Timestamp` objects.
- Use list slicing to extract a sequence of dates.
- The `truncate` method is another alternative for extracting a range of dates..

In [23]:
stocks.loc["2022-03-04"]
stocks.loc[dt.datetime(2022, 3, 4)]
stocks.loc[pd.Timestamp(2022, 3, 4)]

stocks.loc["2022-03-04":"2023-01-01"]
stocks.loc[pd.Timestamp(2022, 3, 4) : pd.Timestamp(2022, 12, 31)]

stocks.truncate("2022-03-04", "2023-01-01")
stocks.truncate(pd.Timestamp(2022, 3, 4), pd.Timestamp(2022, 12, 31))

              Open    High     Low   Close   Volume
Date
2022-03-04  107.51  110.06  107.35  109.43  4402400
2022-03-07  109.30  110.54  108.56  108.95  5047400
2022-03-08  109.43  110.92  107.87  108.62  4887600
2022-03-09  110.11  110.71  108.81  109.08  4403500
2022-03-10  108.68  108.92  106.41  107.47  5326800
...            ...     ...     ...     ...      ...
2022-12-23  126.01  127.15  125.12  126.96  2092500
2022-12-27  127.03  127.92  126.58  127.65  2742400
2022-12-28  127.63  128.00  125.44  125.50  2539500
2022-12-29  126.00  127.51  125.88  126.43  2337200
2022-12-30  125.96  126.29  124.99  126.28  2858000

[209 rows x 5 columns]

- The second argument to `loc` represents the column(s) to target.

In [24]:
stocks.loc["2022-03-04", "Close"]
stocks.loc["2022-03-04", ["Open", "Close"]]
stocks.loc["2022-03-04", "High":"Close"]

High     110.06
Low      107.35
Close    109.43
Name: 2022-03-04 00:00:00, dtype: float64

- Pass a shorter string like `"2025"` or `"2025-03"` to `loc` to select all rows within that year or month.

In [25]:
stocks.loc["2025"]
stocks.loc["2025-03"]

              Open    High     Low   Close   Volume
Date
2025-03-03  249.98  251.20  243.61  245.51  2977700
2025-03-04  244.10  250.70  243.46  248.48  5342100
2025-03-05  246.88  248.02  242.39  246.65  4009800
2025-03-06  245.08  247.39  242.19  244.04  3254400
2025-03-07  241.35  257.06  240.60  256.65  6700200
2025-03-10  256.67  261.47  249.99  252.10  8165500
2025-03-11  251.20  251.90  241.26  244.30  5630600
2025-03-12  245.67  248.40  240.94  244.96  3848800
2025-03-13  244.15  244.61  238.50  241.21  3862400
2025-03-14  238.21  244.30  237.16  243.71  4045200
2025-03-17  244.59  249.87  244.35  248.24  3233900
2025-03-18  247.79  247.85  240.54  242.33  4171900
2025-03-19  243.69  248.92  242.03  247.57  3853600
2025-03-20  239.67  242.19  232.79  238.77  7026800
2025-03-21  237.17  240.63  234.04  239.31  9580100
2025-03-24  242.69  244.17  241.37  243.81  4753300
2025-03-25  243.72  246.21  243.56  245.23  3133800
2025-03-26  246.55  249.57  244.87  245.66  4450100
2025-03-27  245.04  245.62  241.14  241.61  2889300
2025-03-28  241.67  242.94  237.55  239.44  3125300
2025-03-31  238.20  246.20  237.96  244.01  6795000

## The DateOffset Object
- A `DateOffset` object adds time to a `Timestamp` to arrive at a new `Timestamp`.
- The `DateOffset` constructor accepts `days`, `weeks`, `months`, `years` parameters, and more.
- We can pass a `DateOffset` object to the `freq` parameter of the `pd.date_range` function.

In [26]:
stocks = pd.read_csv("ibm.csv", parse_dates=["Date"], index_col="Date").sort_index()
stocks.head()

            Open  High   Low  Close  Volume
Date
1962-01-02  1.48  1.48  1.46   1.46  407940
1962-01-03  1.46  1.48  1.46   1.48  305955
1962-01-04  1.48  1.48  1.46   1.46  274575
1962-01-05  1.46  1.46  1.43   1.43  384405
1962-01-08  1.43  1.43  1.39   1.41  572685

In [27]:
pd.Timestamp(2026, 2, 3) + pd.DateOffset(days=5)
pd.Timestamp(2026, 2, 3) - pd.DateOffset(days=5)
pd.Timestamp(2026, 2, 3) + pd.DateOffset(weeks=5, days=3)

stocks.index + pd.DateOffset(days=5)
stocks.index + pd.DateOffset(months=3)
stocks.index + pd.DateOffset(years=1)
stocks.index - pd.DateOffset(years=1)

stocks.index + pd.DateOffset(
    years=1, months=3, days=2, hours=14, minutes=23, seconds=12
)

DatetimeIndex(['1963-04-04 14:23:12', '1963-04-05 14:23:12',
               '1963-04-06 14:23:12', '1963-04-07 14:23:12',
               '1963-04-10 14:23:12', '1963-04-11 14:23:12',
               '1963-04-12 14:23:12', '1963-04-13 14:23:12',
               '1963-04-14 14:23:12', '1963-04-17 14:23:12',
               ...
               '2027-04-18 14:23:12', '2027-04-22 14:23:12',
               '2027-04-23 14:23:12', '2027-04-24 14:23:12',
               '2027-04-25 14:23:12', '2027-04-28 14:23:12',
               '2027-04-29 14:23:12', '2027-04-30 14:23:12',
               '2027-05-01 14:23:12', '2027-05-02 14:23:12'],
              dtype='datetime64[us]', name='Date', length=16128, freq=None)

## The date_range Function
- The `pd.date_range` function generates a `MultiIndex` of values from a start point to an endpoint.
- We can customize the frequency/gap between each `Timestamp` with the `freq` parameter.
- We can also ask it to generate a certain number of values with the `periods` parameter and either a start or end.

In [28]:
stocks = pd.read_csv("ibm.csv", parse_dates=["Date"], index_col="Date").sort_index()
stocks.head()

            Open  High   Low  Close  Volume
Date
1962-01-02  1.48  1.48  1.46   1.46  407940
1962-01-03  1.46  1.48  1.46   1.48  305955
1962-01-04  1.48  1.48  1.46   1.46  274575
1962-01-05  1.46  1.46  1.43   1.43  384405
1962-01-08  1.43  1.43  1.39   1.41  572685

In [29]:
pd.date_range(start="1991-04-12", end="2026-04-12", freq="1h")
pd.date_range(start="1991-04-12", end="2026-04-12", freq="4h")
pd.date_range(start="1991-04-12", end="2026-04-12", freq="7D")
pd.date_range(start="1991-04-12", freq="7D", periods=200)
pd.date_range(end="1991-04-12", freq="7D", periods=200)
birthdays = pd.date_range(
    start="1991-04-12", end="2026-04-12", freq=pd.DateOffset(years=1)
)
birthdays

DatetimeIndex(['1991-04-12', '1992-04-12', '1993-04-12', '1994-04-12',
               '1995-04-12', '1996-04-12', '1997-04-12', '1998-04-12',
               '1999-04-12', '2000-04-12', '2001-04-12', '2002-04-12',
               '2003-04-12', '2004-04-12', '2005-04-12', '2006-04-12',
               '2007-04-12', '2008-04-12', '2009-04-12', '2010-04-12',
               '2011-04-12', '2012-04-12', '2013-04-12', '2014-04-12',
               '2015-04-12', '2016-04-12', '2017-04-12', '2018-04-12',
               '2019-04-12', '2020-04-12', '2021-04-12', '2022-04-12',
               '2023-04-12', '2024-04-12', '2025-04-12', '2026-04-12'],
              dtype='datetime64[us]', freq='<DateOffset: years=1>')

- Let's extract all of the rows that fell on a given date each year.

In [30]:
stocks[stocks.index.isin(birthdays)]

              Open    High     Low   Close    Volume
Date
1991-04-12   11.42   11.42   11.12   11.16  14876212
1993-04-12    5.79    5.92    5.78    5.82   5854671
1994-04-12    6.30    6.31    6.15    6.20   7900229
1995-04-12   10.29   10.42   10.25   10.37   7962989
1996-04-12   13.84   13.89   13.23   13.39  32472024
1999-04-12   45.26   45.29   44.65   45.24   9392871
2000-04-12   59.27   59.27   55.34   56.36   9293919
2001-04-12   47.99   48.54   47.37   47.89   9822045
2002-04-12   43.81   44.01   42.23   42.83  16546988
2004-04-12   47.50   47.94   47.45   47.62   3255780
2005-04-12   43.99   44.16   43.62   43.91   8817466
2006-04-12   41.95   42.09   41.70   41.77   4084839
2007-04-12   49.84   50.25   49.57   50.17   7411224
2010-04-12   71.06   71.28   70.88   70.95   4175946
2011-04-12   91.97   92.20   91.38   91.91   4038188
2012-04-12  116.10  117.68  116.01  117.54   3064362
2013-04-12  122.75  123.15  122.16  123.09   3311008
2016-04-12   94.50   94.81   93.85   94.51   3761207
2017-04-12  111.89  112.00  111.23  111.65   3427637
2018-04-12  106.73  108.25  106.67  107.63   5898812
2019-04-12  102.85  102.98  102.45  102.91   3032249
2021-04-12  106.35  106.63  105.43  106.01   3926684
2022-04-12  109.26  110.05  108.53  108.87   2691000
2023-04-12  118.31  118.76  116.29  116.62   3957500
2024-04-12  174.69  175.80  172.49  173.04   3547400

## Specialized Date Offsets
- Pandas nests more specialized date offsets in `pd.tseries.offsets`.
- The offsets represent custom spans of time (month end, quarter end, year begin, etc).
- Use `+` to move time forward into the future.
- Use `-` to move time backward into the past.

In [31]:
stocks = pd.read_csv("ibm.csv", parse_dates=["Date"], index_col="Date").sort_index()
stocks.head()

            Open  High   Low  Close  Volume
Date
1962-01-02  1.48  1.48  1.46   1.46  407940
1962-01-03  1.46  1.48  1.46   1.48  305955
1962-01-04  1.48  1.48  1.46   1.46  274575
1962-01-05  1.46  1.46  1.43   1.43  384405
1962-01-08  1.43  1.43  1.39   1.41  572685

In [32]:
stocks.index + pd.tseries.offsets.MonthEnd()
stocks.index - pd.tseries.offsets.MonthEnd()

stocks.index + pd.tseries.offsets.QuarterEnd()
stocks.index + pd.tseries.offsets.QuarterEnd(startingMonth=3)
stocks.index - pd.tseries.offsets.QuarterEnd()

stocks.index + pd.tseries.offsets.QuarterBegin()
stocks.index + pd.tseries.offsets.QuarterBegin(startingMonth=1)

stocks.index + pd.tseries.offsets.YearEnd()
stocks.index + pd.tseries.offsets.YearEnd(n=2)
stocks.index + pd.tseries.offsets.YearBegin()
stocks.index - pd.tseries.offsets.YearBegin()

DatetimeIndex(['1962-01-01', '1962-01-01', '1962-01-01', '1962-01-01',
               '1962-01-01', '1962-01-01', '1962-01-01', '1962-01-01',
               '1962-01-01', '1962-01-01',
               ...
               '2026-01-01', '2026-01-01', '2026-01-01', '2026-01-01',
               '2026-01-01', '2026-01-01', '2026-01-01', '2026-01-01',
               '2026-01-01', '2026-01-01'],
              dtype='datetime64[us]', name='Date', length=16128, freq=None)

## Timedeltas
- A `Timedelta` is a pandas object that represents a duration (an amount of time).
- Subtracting two `Timestamp` objects will yield a `Timedelta` object (this applies to subtracting a `Series` from another `Series`).
- The `Timedelta` constructor accepts parameters for time as well as string descriptions.

In [33]:
pd.Timestamp("2026-03-31 12:30:48") - pd.Timestamp("2026-03-20 19:25:59")

pd.Timedelta(days=3, hours=2, minutes=5)
pd.Timedelta("3 days 2 hours 5 minutes")

Timedelta('3 days 02:05:00')

In [34]:
ecommerce = pd.read_csv(
    "ecommerce.csv",
    index_col="ID",
    parse_dates=["order_date", "delivery_date"],
    date_format="%m/%d/%y",
)

ecommerce.head()

   order_date delivery_date
ID
1  1998-05-24    1999-02-05
2  1992-04-22    1998-03-06
4  1991-02-10    1992-08-26
5  1992-07-21    1997-11-20
7  1993-09-02    1998-06-10

In [35]:
ecommerce["delivery_time"] = ecommerce["delivery_date"] - ecommerce["order_date"]
ecommerce.head()

   order_date delivery_date delivery_time
ID
1  1998-05-24    1999-02-05      257 days
2  1992-04-22    1998-03-06     2144 days
4  1991-02-10    1992-08-26      563 days
5  1992-07-21    1997-11-20     1948 days
7  1993-09-02    1998-06-10     1742 days

In [36]:
ecommerce["twice_as_long"] = ecommerce["delivery_date"] + ecommerce["delivery_time"]
ecommerce.head()

   order_date delivery_date delivery_time twice_as_long
ID
1  1998-05-24    1999-02-05      257 days    1999-10-20
2  1992-04-22    1998-03-06     2144 days    2004-01-18
4  1991-02-10    1992-08-26      563 days    1994-03-12
5  1992-07-21    1997-11-20     1948 days    2003-03-22
7  1993-09-02    1998-06-10     1742 days    2003-03-18

In [37]:
ecommerce["delivery_time"].max()
ecommerce["delivery_time"].min()
ecommerce["delivery_time"].mean()
ecommerce["delivery_time"].sort_values()

ID
898      8 days
612      9 days
19       9 days
994     10 days
310     16 days
         ...
331   3379 days
130   3423 days
904   3562 days
314   3580 days
884   3583 days
Name: delivery_time, Length: 501, dtype: timedelta64[us]